### ISSUE TITLE
添加List: justswap

### ISSUE THREAD

**Issue by neiljiang8511** [justswaporg/justlists#1]
提交之前请删除下面的话:
**如果您没按照要求提交正确的list样式，您的issue将会被删除**

**您提交的list json格式必须满足下面链接中定义的例子格式**

https://github.com/justswaporg/justlists/

检查清单
- [x] **我已知晓这里不是提交token的地方**
- [x] 我已经测试过要提交的List URL能够在`justswap.org`的`添加列表`中进行添加.
- [x] 我已知晓提交的issue不能确保通过并且相应的List不确保能在jsutlists网站中显示.

**请提供以下的信息**
List的URL必须以HTTPS开头.

List URL: baidu.com
List 名称: justswap
List 提交者的网站或主页:just.network

**Comment by JustSwapTeam** [comment]
你的URL错误

**Comment by neiljiang8511** [comment]
明显是对的，好吗

**Comment by JustSwapTeam** [comment]
该issue无效，将会关闭
