### ISSUE TITLE
Add JustList: {Reg Fiance}

### ISSUE THREAD

**Issue by huy1001nguyen** [justswaporg/justlists#1017]
{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"REG",
            "address":"TPycf1hKwk4ndCWNQ5LuAAR2Ko8hNGLBRR",
            "chainId":1,
            "decimals":6,
            "name":"Reg Finance",
            "logoURI":"https://coin.top/production/upload/logo/1003886.png?t=1617948485847"
        },

    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
