### ISSUE TITLE
Add JustList: {GL}

### ISSUE THREAD

**Issue by gearlove** [justswaporg/justlists#1061]
{"symbol":"GL","address":"TU6k7rrR2bqLagEt77o1HayNCJCvFH1Eas","chainId":1,"decimals":3,"name":"Gear Love","logoURI":"https://coin.top/production/upload/logo/TU6k7rrR2bqLagEt77o1HayNCJCvFH1Eas.png"}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
