### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by salikate** [justswaporg/justlists#1119]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

[Just List CHITA INU (CHI).txt](https://github.com/justswaporg/justlists/files/6368776/Just.List.CHITA.INU.CHI.txt)

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
