### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by WazzlDog** [justswaporg/justlists#112]
{
	"name": "WIP",
	"logoURI": "https://coin.top/production/upload/logo/TAmnhcrsFY7oGspb67ZETVKYHdYQZj8znQ.png?t=1611806824796",
	"timestamp": 1610222146000,
	"tokens": [{
			"chainId": 1,
			"address": "TVAWJiMWKn3pLxkjmZ9LwLuKX1i73Cpzsg",
			"name": "WipSwap",
			"symbol": "WIP",
			"decimals": 8,
			"logoURI": "https://coin.top/production/upload/logo/TAmnhcrsFY7oGspb67ZETVKYHdYQZj8znQ.png?t=1611806824796"
		},
	],
	"version": {
		"major": 6,
		"minor": 6,
		"patch": 6
	}
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
