### ISSUE TITLE
添加JustList: {JustList name}

### ISSUE THREAD

**Issue by chuanzhang666** [justswaporg/justlists#1179]
{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"BNF",
            "address":"TDRMzSYCTydbAdHq89nj1dYLeLhhctJuTK",
            "chainId":1,
            "decimals":8,
            "name":"BNF",
            "logoURI":"https://coin.top/production/upload/logo/TDRMzSYCTydbAdHq89nj1dYLeLhhctJuTK.png"
        },
        {
            "symbol":"BTC",
            "address":"TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
            "chainId":1,
            "decimals":8,
            "name":"Bitcoin",
            "logoURI":"https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
        },

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
