### ISSUE TITLE
list

### ISSUE THREAD

**Issue by CanisTokens** [justswaporg/justlists#1199]
{
	"name": "Tron Alliance Listssd",
	"logoURI": "https://list.tronalliance.cc/fav.ico",
	"timestamp": 1617874934413,
	"version": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"tokens": [{
		"symbol": "USDT",
		"address": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
		"chainId": 1,
		"decimals": 6,
		"name": "Tether USD",
		"logoURI": "https://coin.top/production/logo/usdtlogo.png"
	}, {
		"symbol": "USDJ",
		"address": "TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT",
		"chainId": 1,
		"decimals": 18,
		"name": "JUST Stablecoin",
		"logoURI": "https://coin.top/production/logo/usdj.png"
	}, {
		"symbol": "JST",
		"address": "TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9",
		"chainId": 1,
		"decimals": 18,
		"name": "JUST GOV",
		"logoURI": "https://coin.top/production/logo/just_icon.png"
	}, {
		"symbol": "WBTT",
		"address": "TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt",
		"chainId": 1,
		"decimals": 6,
		"name": "Wrapped BTT",
		"logoURI": "https://coin.top/production/logo/TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt.png"
	}, {
		"symbol": "WIN",
		"address": "TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7",
		"chainId": 1,
		"decimals": 6,
		"name": "WINK",
		"logoURI": "https://coin.top/profile_images/JKtJTydD_400x400.jpg"
	}, {
		"symbol": "BTC",
		"address": "TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
		"chainId": 1,
		"decimals": 8,
		"name": "Bitcoin",
		"logoURI": "https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
	}, {
		"symbol": "ETH",
		"address": "THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF",
		"chainId": 1,
		"decimals": 18,
		"name": "Ethereum",
		"logoURI": "https://coin.top/production/logo/THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF.png"
	}, {
		"symbol": "SUN",
		"address": "TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9",
		"chainId": 1,
		"decimals": 18,
		"name": "SUN TOKEN",
		"logoURI": "https://coin.top/production/logo/SUNLogo.178d4636.png"
	}, {
		"symbol": "FIST",
		"address": "TL6K6iaEkn8kdnJ79a8Be3S4RFf4pFkGE8",
		"chainId": 1,
		"decimals": 6,
		"name": "FistToken",
		"logoURI": "https://coin.top/production/upload/logo/TL6K6iaEkn8kdnJ79a8Be3S4RFf4pFkGE8.png?t=1600420149866"
	}, {
		"symbol": "WETH",
		"address": "TXWkP3jLBqRGojUih1ShzNyDaN5Csnebok",
		"chainId": 1,
		"decimals": 18,
		"name": "Wrapped ETH",
		"logoURI": "https://coin.top/production/logo/TXWkP3jLBqRGojUih1ShzNyDaN5Csnebok.png"
	}, {
		"symbol": "WBTC",
		"address": "TXpw8XeWYeTUd4quDskoUqeQPowRh4jY65",
		"chainId": 1,
		"decimals": 8,
		"name": "Wrapped BTC",
		"logoURI": "https://coin.top/production/logo/TXpw8XeWYeTUd4quDskoUqeQPowRh4jY65.png"
	}, {
		"symbol": "WOK",
		"address": "TXMKm8FSp6zcm3cdgkgcM1fwdkuJbZ4Hgv",
		"chainId": 1,
		"decimals": 18,
		"name": "Walker",
		"logoURI": "https://coin.top/production/upload/logo/TXMKm8FSp6zcm3cdgkgcM1fwdkuJbZ4Hgv.png?t=1615198066362"
	}, {
		"symbol": "OSK",
		"address": "TDk91SWz2GvwfZwMTGX21d4ngUUH8YZZAv",
		"chainId": 1,
		"decimals": 18,
		"name": "OSK",
		"logoURI": "https://coin.top/production/upload/logo/TDk91SWz2GvwfZwMTGX21d4ngUUH8YZZAv.png?t=1611479452774"
	}, {
		"symbol": "LBOO",
		"address": "TSCjRpPbD9omYhx49fpZfsnpxoTv9udBVm",
		"chainId": 1,
		"decimals": 6,
		"name": "CreateDream",
		"logoURI": "https://coin.top/production/upload/logo/TSCjRpPbD9omYhx49fpZfsnpxoTv9udBVm.png?t=1611159314370"
	}, {
		"symbol": "SSK",
		"address": "TW1sqqq7UphAqGNHDXSLXsEainYHJuQeyC",
		"chainId": 1,
		"decimals": 18,
		"name": "SunStake",
		"logoURI": "https://coin.top/production/upload/logo/TW1sqqq7UphAqGNHDXSLXsEainYHJuQeyC.png?t=1600475896144"
	}, {
		"symbol": "FC",
		"address": "TKzf6cF5RsxzV7Shcf8MpuRRJcfDiG1hDn",
		"chainId": 1,
		"decimals": 6,
		"name": "Filecoin Community Token",
		"logoURI": "https://coin.top/production/upload/logo/TKzf6cF5RsxzV7Shcf8MpuRRJcfDiG1hDn.png?t=1609755361692"
	}, {
		"symbol": "Pearl",
		"address": "TGbu32VEGpS4kDmjrmn5ZZJgUyHQiaweoq",
		"chainId": 1,
		"decimals": 18,
		"name": "Pearl.finance",
		"logoURI": "http://coin.top/production/logo/PEARL.png"
	}, {
		"symbol": "GFC",
		"address": "TWd7vJKaGmpq6oHgpHBqHHPG8JP2XErkTH",
		"chainId": 1,
		"decimals": 6,
		"name": "GFC",
		"logoURI": "https://coin.top/production/upload/logo/TWd7vJKaGmpq6oHgpHBqHHPG8JP2XErkTH.png?t=1610615429690"
	}, {
		"symbol": "LUMI",
		"address": "TDBNKiYQ8yfJtT5MDP3byu7f1npJuG2DBN",
		"chainId": 1,
		"decimals": 6,
		"name": "LUMI Credits",
		"logoURI": "https://coin.top/production/upload/logo/TDBNKiYQ8yfJtT5MDP3byu7f1npJuG2DBN.png?t=1601521357667"
	}, {
		"symbol": "TUSD",
		"address": "TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4",
		"chainId": 1,
		"decimals": 18,
		"name": "TrueUSD",
		"logoURI": "https://coin.top/production/upload/logo/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4.jpeg?t=1617769013754"
	}, {
		"symbol": "LAFIT",
		"address": "TSSKoX392dkKxSYHecjNkzgUQsJ3UUEkRu",
		"chainId": 1,
		"decimals": 6,
		"name": "LafitChain",
		"logoURI": "https://coin.top/production/upload/logo/TSSKoX392dkKxSYHecjNkzgUQsJ3UUEkRu.png?t=1605286523201"
	}, {
		"symbol": "DJV",
		"address": "TQDRp2VCRc3s9X1zx2CgLoauPp44iQVaw8",
		"chainId": 1,
		"decimals": 6,
		"name": "Dejave",
		"logoURI": "https://coin.top/production/upload/logo/TQDRp2VCRc3s9X1zx2CgLoauPp44iQVaw8.jpeg?t=1613569635471"
	}, {
		"symbol": "DGP",
		"address": "TNuvvN2MemD1sjaifZpgMaKzRLyQEVPHbx",
		"chainId": 1,
		"decimals": 6,
		"name": "DGPToken",
		"logoURI": "https://coin.top/production/upload/logo/TNuvvN2MemD1sjaifZpgMaKzRLyQEVPHbx.png?t=1609220157320"
	}, {
		"symbol": "AIS",
		"address": "TRZPqchWTRUzXNGNWPoAqLB7H8J2j3saf8",
		"chainId": 1,
		"decimals": 18,
		"name": "AISwap",
		"logoURI": "https://coin.top/production/upload/logo/TRZPqchWTRUzXNGNWPoAqLB7H8J2j3saf8.png?t=1606228331790"
	}, {
		"symbol": "LTC",
		"address": "TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd",
		"chainId": 1,
		"decimals": 8,
		"name": "Litecoin",
		"logoURI": "https://coin.top/production/logo/TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd.png"
	}, {
		"symbol": "DIVS",
		"address": "TRXmYPy2AXZxacoSbKGjiVto8K1EqwexU7",
		"chainId": 1,
		"decimals": 8,
		"name": "Divs",
		"logoURI": "https://coin.top/production/upload/logo/TRXmYPy2AXZxacoSbKGjiVto8K1EqwexU7.png?t=1611715976242"
	}, {
		"symbol": "MOMO",
		"address": "TDKmefRcHcSUj4RoGkaUy2AxJzyqG1xr1z",
		"chainId": 1,
		"decimals": 6,
		"name": "MOMO",
		"logoURI": "https://coin.top/production/upload/logo/TDKmefRcHcSUj4RoGkaUy2AxJzyqG1xr1z.png?t=1611135506269"
	}, {
		"symbol": "DICE",
		"address": "TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd",
		"chainId": 1,
		"decimals": 6,
		"name": "TRONbetDice",
		"logoURI": "https://coin.top/production/logo/TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd.jpg"
	}, {
		"symbol": "LACv2",
		"address": "TWtM4WLpp95MuhmvRoSq1rn7u6VNd2HdDv",
		"chainId": 1,
		"decimals": 6,
		"name": "LAC V2",
		"logoURI": "https://coin.top/production/upload/logo/TWtM4WLpp95MuhmvRoSq1rn7u6VNd2HdDv.png?t=1604947856393"
	}, {
		"symbol": "JKT",
		"address": "TNBJrsrUD764RftEk3ifTWBu7ijC3KneSA",
		"chainId": 1,
		"decimals": 6,
		"name": "JianKangToken",
		"logoURI": "https://coin.top/production/upload/logo/TNBJrsrUD764RftEk3ifTWBu7ijC3KneSA.jpeg?t=1608303992644"
	}, {
		"symbol": "SHDAO",
		"address": "TPSZJU1kFxymUTsgpYGD9JkAVbx1VXX1yq",
		"chainId": 1,
		"decimals": 6,
		"name": "SHDAO",
		"logoURI": "https://coin.top/production/upload/logo/TPSZJU1kFxymUTsgpYGD9JkAVbx1VXX1yq.png?t=1614756704534"
	}, {
		"symbol": "ETVPro",
		"address": "TLboKdNJtMsLeseiozgjFHy4yQ6o4SwrEi",
		"chainId": 1,
		"decimals": 18,
		"name": "ETVPro",
		"logoURI": "https://coin.top/production/upload/logo/TLboKdNJtMsLeseiozgjFHy4yQ6o4SwrEi.png?t=1607882448722"
	}, {
		"symbol": "DZI",
		"address": "TLi2o9XadMAonBJvzoj1kHBkNe6Nh1SaZ3",
		"chainId": 1,
		"decimals": 9,
		"name": "DeFinition Token",
		"logoURI": "https://coin.top/production/upload/logo/TLi2o9XadMAonBJvzoj1kHBkNe6Nh1SaZ3.png?t=1598015109867"
	}, {
		"symbol": "BRG",
		"address": "TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC",
		"chainId": 1,
		"decimals": 6,
		"name": "Bridge Token",
		"logoURI": "https://coin.top/production/upload/logo/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC.png?t=1598197424550"
	}, {
		"symbol": "LIVE",
		"address": "TVgAYofpQku5G4zenXnvxhbZxpzzrk8WVK",
		"chainId": 1,
		"decimals": 6,
		"name": "TRONbetLive",
		"logoURI": "https://coin.top/production/upload/logo/TVgAYofpQku5G4zenXnvxhbZxpzzrk8WVK.png?t=1569566505980"
	}, {
		"symbol": "MIX",
		"address": "TMNwVthrDoE8yWNb2F9kxQEzwKEpQhdh3d",
		"chainId": 1,
		"decimals": 6,
		"name": "MIX",
		"logoURI": "https://coin.top/production/upload/logo/TMNwVthrDoE8yWNb2F9kxQEzwKEpQhdh3d.png?t=1616578450890"
	}, {
		"symbol": "EVER",
		"address": "TEsfLEHgNRR37SmeACtJ8DRvDWFtUvoiNM",
		"chainId": 1,
		"decimals": 18,
		"name": "EverToken",
		"logoURI": "https://coin.top/production/upload/logo/TEsfLEHgNRR37SmeACtJ8DRvDWFtUvoiNM.png?t=1611655089521"
	}, {
		"symbol": "TMX",
		"address": "TLv2K6GuJxdw157HirogRCGfJTaBwhJD4q",
		"chainId": 1,
		"decimals": 9,
		"name": "TMX",
		"logoURI": "https://coin.top/production/upload/logo/TLv2K6GuJxdw157HirogRCGfJTaBwhJD4q.png?t=1617073993072"
	}, {
		"symbol": "MYTH",
		"address": "TVXSQXmrj1UHPaUWtDbtgvx5YpcGnZrdvm",
		"chainId": 1,
		"decimals": 6,
		"name": "Myth Chain",
		"logoURI": "https://coin.top/production/upload/logo/TVXSQXmrj1UHPaUWtDbtgvx5YpcGnZrdvm.png?t=1614320963723"
	}, {
		"symbol": "CORAL",
		"address": "TUoWQfYcYrDxumQoiC3ZSToz5VnxsU9DmM",
		"chainId": 1,
		"decimals": 6,
		"name": "CORAL",
		"logoURI": "https://coin.top/production/upload/logo/TUoWQfYcYrDxumQoiC3ZSToz5VnxsU9DmM.png?t=1612717734495"
	}, {
		"symbol": "TEWKEN",
		"address": "TBhxyECmAg3uCqqmEHQvGJbrgj9cn1yMZ1",
		"chainId": 1,
		"decimals": 6,
		"name": "Tewkenaire",
		"logoURI": "https://coin.top/production/upload/logo/TBhxyECmAg3uCqqmEHQvGJbrgj9cn1yMZ1.png?t=1586829704545"
	}, {
		"symbol": "DFK",
		"address": "TSAqYo6BeyMQhzHbj2xHu2enXxQnetx6yz",
		"chainId": 1,
		"decimals": 8,
		"name": "DefiKing",
		"logoURI": "https://coin.top/production/upload/logo/TSAqYo6BeyMQhzHbj2xHu2enXxQnetx6yz.png?t=1597741875858"
	}, {
		"symbol": "XG",
		"address": "TKbkX6nfmxdw7Vz56HxxuunZg1fdKUMtaM",
		"chainId": 1,
		"decimals": 8,
		"name": "XGAME",
		"logoURI": "https://coin.top/production/upload/logo/TKbkX6nfmxdw7Vz56HxxuunZg1fdKUMtaM.png?t=1603086668399"
	}, {
		"symbol": "FILA",
		"address": "TYtgUMrB1H72SqQDNCVNRn1DNYxqn8Qfxr",
		"chainId": 1,
		"decimals": 18,
		"name": "FILA",
		"logoURI": "https://coin.top/production/upload/logo/TYtgUMrB1H72SqQDNCVNRn1DNYxqn8Qfxr.png?t=1617446832457"
	}, {
		"symbol": "PNUT",
		"address": "TPZddNpQJHu8UtKPY1PYDBv2J5p5QpJ6XW",
		"chainId": 1,
		"decimals": 6,
		"name": "Nutbox Peanuts",
		"logoURI": "https://coin.top/production/upload/logo/TPZddNpQJHu8UtKPY1PYDBv2J5p5QpJ6XW.jpeg?t=1603183073762"
	}, {
		"symbol": "ACF",
		"address": "THsAGVMv1zwJb57ujHKEnAuxuPeHC3VLVZ",
		"chainId": 1,
		"decimals": 18,
		"name": "Auction platform",
		"logoURI": "https://coin.top/production/upload/logo/THsAGVMv1zwJb57ujHKEnAuxuPeHC3VLVZ.jpeg?t=1614851387973"
	}, {
		"symbol": "RING",
		"address": "TL175uyihLqQD656aFx3uhHYe1tyGkmXaW",
		"chainId": 1,
		"decimals": 18,
		"name": "Evolution Land Global Token",
		"logoURI": "https://coin.top/production/logo/TL175uyihLqQD656aFx3uhHYe1tyGkmXaW.png"
	}, {
		"symbol": "XYC",
		"address": "TCrzjWFshRi5iBkLZ9jT6o28ZnDTw2HnBV",
		"chainId": 1,
		"decimals": 6,
		"name": "XYChain",
		"logoURI": "https://coin.top/production/upload/logo/TCrzjWFshRi5iBkLZ9jT6o28ZnDTw2HnBV.png?t=1617640622178"
	}, {
		"symbol": "GLDI",
		"address": "TQx2dDDHv8xVr5HEYRygjWizYdzDmdUHNp",
		"chainId": 1,
		"decimals": 6,
		"name": "GoldenDiamonds",
		"logoURI": "https://coin.top/production/upload/logo/TQx2dDDHv8xVr5HEYRygjWizYdzDmdUHNp.png?t=1610301580324"
	},
{
		"symbol": "CIS",
		"address": "TWNmtJ75HTsMn5uKH5YKsG5iVJDWzSaSzG",
		"chainId": 1,
		"decimals": 18,
		"name": "Canis",
		"logoURI": "https://coin.top/production/upload/logo/TWNmtJ75HTsMn5uKH5YKsG5iVJDWzSaSzG.png?t=1621094863709"
	},
 {
		"symbol": "MILK",
		"address": "TYaAqxSMub4VSqZFczKDk6NzQp9N9Mcik2",
		"chainId": 1,
		"decimals": 6,
		"name": "Milk",
		"logoURI": "https://coin.top/production/upload/logo/TYaAqxSMub4VSqZFczKDk6NzQp9N9Mcik2.jpeg?t=1604524633828"
	}]
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
