### ISSUE TITLE
Arabwe

### ISSUE THREAD

**Issue by mfayedinfo** [justswaporg/justlists#1201]
{
   "name": "Arabwe", #Arabwe
   "logoURI": "https://coin.top/production/upload/logo/1003979.png", 
   "tokens": [{ "chainId": 1003979
           "address": "TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9", #Token address
           "name": "Arabwe"
           "symbol": "Arabwe"
           "decimals": 6
           "logoURI": "https://coin.top/production/upload/logo/1003979.png" 
       }

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
