### ISSUE TITLE
Add JustList: PHUCKS

### ISSUE THREAD

**Issue by abacabltd** [justswaporg/justlists#1231]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/abacabltd/justlists/blob/main/phuck.ts

Checklist
- [ x] **I understand that this is not the place to request a token listing.**
- [x ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://justswap.org/#/home?tokenAddress=TFUusM3Nxu63BZX95DsZZAhhwyftRkVjo6
JustList Name: PHUCKS
Link to the official homepage of the JustList manager: https://givephuck.com

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
