### ISSUE TITLE
Add JustList: {Kiwidefi}

### ISSUE THREAD

**Issue by KiwiDefi** [justswaporg/justlists#1239]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [ *] **I understand that this is not the place to request a token listing.**
- [* ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [* ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://api.kiwidefi.com/kiwidefi.json
JustList Name: Kiwidefi
Link to the official homepage of the JustList manager: https://kiwidefi.com
[justlist kwd.txt](https://github.com/justswaporg/justlists/files/6521212/justlist.kwd.txt)

**Comment by stevenstc** [comment]
good luck

**Comment by Minona1205** [comment]
nice good luck

**Comment by jz2120100058** [comment]
We found that all the tokens in the application List you submitted except “KWD, WDCN” have been included in the Tron Alliance List. Since there is only two new tokens, we suggest adding “KWD, WDCN” to the existing List, such as Tron Alliance List:https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.
