### ISSUE TITLE
Add JustList: Moslim coin

### ISSUE THREAD

**Issue by moslimcoin** [justswaporg/justlists#1242]
{
   "name": "TokenListExample", #List name
   "logoURI": "https://coin.top/production/upload/logo/TQSc6KYznjfoHDec4aLssJ6ognBazcbsEW.png?t=1621546786969", #List logo uri
   "timestamp": 1610339529000, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TQSc6KYznjfoHDec4aLssJ6ognBazcbsEW", #Token address
           "name": "Moslim_coin", #Token name
           "symbol": "MSL", #Token symbol
           "decimals": 18, #Token decimals
           "logoURI": "https://coin.top/production/upload/logo/TQSc6KYznjfoHDec4aLssJ6ognBazcbsEW.png?t=1621546786969" #Token logo uri
       

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/justswaporg/justlists/issues/1242
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
