### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by ericchan112211** [justswaporg/justlists#1246]
{
    "name": "OptuzToken", 
    "logoURI": "https://coin.top/production/upload/logo/TD7SQai4CsV5nW7inQPKz5j9uVxTYNWUk7.png", 
    "timestamp": 1610339529000, 
    "tokens": [{
            "chainId": 1, 
            "address": "TD7SQai4CsV5nW7inQPKz5j9uVxTYNWUk7", 
            "name": "OPTUZ",
            "symbol": "OPZ", 
            "decimals": 8, 
            "logoURI": "https://coin.top/production/upload/logo/TD7SQai4CsV5nW7inQPKz5j9uVxTYNWUk7.png"
        }
    ],
    "version": {
        "major": 1, 
        "minor": 0, 
        "patch": 0  
    }
 }

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://optuz.io/
JustList Name: OPTUZ
Link to the official homepage of the JustList manager: https://optuz.io/login

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
