### ISSUE TITLE
Add JustList: {Yordan Decentralized Token}

### ISSUE THREAD

**Issue by rexdev-labs** [justswaporg/justlists#1321]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://raw.githubusercontent.com/rexdev-labs/justlistydt/master/justlistydt
JustList Name: Yordan Decentralized Token
Link to the official homepage of the JustList manager:https://ydt.yordan.vip/

**Comment by stevenstc** [comment]
good luck

**Comment by KAMLEGENDZ** [comment]
add pax trc10 pls : "TUx2bixRHR4TV9ZGNztFzk9nAcEQ2t4Le5"

**Comment by stevenstc** [comment]
NO

**Comment by jz2120100058** [comment]
Thanks for your application.
Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
Please share more info to us at: justlists@outlook.com
It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
Thanks

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.
