### ISSUE TITLE
Add JustList: {WGFNC}

### ISSUE THREAD

**Issue by elbernn** [justswaporg/justlists#136]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x ] **I understand that this is not the place to request a token listing.**
- [ x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/elbernn/WGFNC/blob/main/WGFNC
JustList Name: WGFNC
Link to the official homepage of the JustList manager: https://grafenocoin.com

 "name": "Wrapped GrafenoCoin WGFNC", #List name
   "logoURI": "https://coin.top/production/upload/logo/TESK4j3eehtcjTVv2RrhPYwtZM3aH5EySM.png, #List logo uri
   "timestamp": 1603213505765, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TESK4j3eehtcjTVv2RrhPYwtZM3aH5EySM", #Token address
           "name": "Wrapped GrafenoCoin", #Token name
           "symbol": "WGFNC", #Token symbol
           "decimals": 6, #Token decimals
           "logoURI": "https://coin.top/production/upload/logo/TESK4j3eehtcjTVv2RrhPYwtZM3aH5EySM.png" #Token logo uri

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
