### ISSUE TITLE
Add JustList: Peso Digital

### ISSUE THREAD

**Issue by stevenstc** [justswaporg/justlists#1416]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://pesodigital.ml/list-peso-digital.json
JustList Name: Peso Digital
Link to the official homepage of the JustList manager: https://pesodigital.ml

**Comment by stevenstc** [comment]
Here you find tokens of seriously business, i was working them, and have and order of relevance of each token.

**Comment by stevenstc** [comment]
In addition to that, it has a much more logical order for the tokens and more comfortable to search, we are constantly updating it to be up to date

**Comment by jz2120100058** [comment]
We found that all the tokens in the application List you submitted except “SITE, BXR” have been included in the Tron Alliance List. Since there is only two new tokens, we suggest adding “SITE, BXR” to the existing List, such as Tron Alliance List:https://github.com/listtronalliance/tronalliance.

**Comment by stevenstc** [comment]
In addition to those two currencies that you mention, you should really review the order and the currencies that you have since I organize them in a more specific order of relevance

**Comment by jz2120100058** [comment]
Let’s discuss it first. If there is any progress, we will reply in time.

**Comment by jz2120100058** [comment]
Thanks for your application.
Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
Please share more info to us at: justlists@outlook.com
It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
Thanks

**Comment by l148** [comment]
MERIT合约地址公开http://t.cn/A6cmLh5Q&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MERIT币目前支持TP钱包&nbsp;&nbsp;&nbsp;比特派钱包&nbsp;&nbsp;&nbsp;BiTKeep钱包&nbsp;&nbsp;&nbsp;麦子钱包&nbsp;&nbsp;HyperPay钱包&nbsp;&nbsp;波宝钱包，同时转账，转账需要能量和宽带。需要在社区群内发你的收币地址。钱包需要保管好自己的助记词。币种添加好合约地址。我们欢迎新成员加入转账测试。MERIT币的成员也是自由自愿方式加入，人员自由创建地址&nbsp;&nbsp;&nbsp;MERIT社区合约地址公开性。微信如果打不开可以复制到浏览器打开复制合约地址。新建电报群http://t.cn/A6VSfNjC&nbsp;&nbsp;新建微博粉丝群http://t.cn/A67xwqUI&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;电报群http://t.cn/A6fGUML3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MERIT&nbsp;蛋蛋社区
http://t.cn/A6IbzQNS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;点击链接加入群聊【MERIT蛋蛋社区群】：https://jq.qq.com/?_wv=1027&amp;k=Mlk5F1e2


---Original---
From: ***@***.***&gt;
Date: Fri, Jan 7, 2022 18:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [justswaporg/justlists] Add JustList: Peso Digital (#1416)




 
Thanks for your application.
 Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
 Please share more info to us at: ***@***.***
 It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
 Thanks
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stevenstc** [comment]
steven.cabrera@pesodigital.ml 
pesodigital.ml

**Comment by l148** [comment]
MERIT合约地址公开http://t.cn/A6cmLh5Q                                                                                   MERIT币目前支持TP钱包   比特派钱包   BiTKeep钱包   麦子钱包  HyperPay钱包  波宝钱包，同时转账，转账需要能量和宽带。需要在社区群内发你的收币地址。每个人每个地址空投1000个Merit测试。钱包需要保管好自己的助记词。币种添加好合约地址。我们欢迎新成员加入转账测试。MERIT币的成员也是自由自愿方式加入，人员自由创建地址   MERIT社区合约地址公开性。微信如果打不开可以复制到浏览器打开复制合约地址。新建电报群http://t.cn/A6VSfNjC  新建微博粉丝群http://t.cn/A67xwqUI     电报群http://t.cn/A6fGUML3     MERIT 蛋蛋社区http://t.cn/A6IbzQNS            点击链接加入群聊【MERIT蛋蛋社区群】：https://jq.qq.com/?_wv=1027&k=Mlk5F1e2                                            https://f.wps.cn/w/MZ6TKLJc/邀你填写「蛋蛋社区，姓名，地址接龙」发自我的荣耀手机-------- 原始邮件 --------发件人： Steven Cabrera Londoño ***@***.***>日期： 2022年1月11日周二 清晨5:45收件人： justswaporg/justlists ***@***.***>抄送： l148 ***@***.***>, Comment ***@***.***>主    题： Re: [justswaporg/justlists] Add JustList: Peso Digital (#1416)
***@***.***
pesodigital.ml

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.

**Comment by stevenstc** [comment]
If I answer, I am waiting to receive an email and I did not receive answers here on github either.

**Comment by jz2120100058** [comment]
Thanks for your application.
Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
Please share more info to us at: [support@sunswap.com](mailto:support@sunswap.com)
It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
Thanks
