### ISSUE TITLE
BZB

### ISSUE THREAD

**Issue by bzbecology** [justswaporg/justlists#142]
检查清单
- [ ] **我已知晓此issue不是提交token而是提交JustList**
- [ ] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [ ] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: https://justswap.org/?lang=zh-CN#/home?tokenAddress=TEfnpLH77nr5VuPBoFPmak4KrwV3TkcFwq&type=swap
JustList 名称: BZB
JustList 提交者的网站或主页: https://www.bzbmining.com

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
