### ISSUE TITLE
Add JustList: {CGA}

### ISSUE THREAD

**Issue by cga-token** [justswaporg/justlists#1425]
https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [ OK] **I understand that this is not the place to request a token listing.**
- [OK ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ OK] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: http://cgatokens.com/
JustList Name: CGA (Cost Global Advertising)
Link to the official homepage of the JustList manager:
https://t.me/CGA_Token
https://twitter.com/CgaToken
https://www.facebook.com/CGAToken
https://www.instagram.com/cga_token/
https://tronscan.org/#/token20/TQewb94VLthHhj56ZroKNn1aA5noTam93D

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
