### ISSUE TITLE
The Flash currency

### ISSUE THREAD

**Issue by Theflashcurrency-TFC** [justswaporg/justlists#1465]
Checklist
- [x] #1468
- [x] #1467
- [x] #1466

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL:https://github.com/thienvu333/theflashcurrency-TFC/blob/6365d6314127578c1513faced02475c7835698eb/tfc.java
JustList Name: The Flash currency
Link to the official homepage of the JustList manager: https://github.com/thienvu333/theflashcurrency-TFC

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
