### ISSUE TITLE
The Flash Currency-TFC

### ISSUE THREAD

**Issue by Theflashcurrency-TFC** [justswaporg/justlists#1477]
"name": "The Flash Currency",
"website": " https://theflashcurrency.com/ ",
"description": "TFC is the official token of www.theflashcurrency.com .",
"explorer": " https://tronscan.org/#/token/1004117 ",
" loại ":" TRC10 ",
" biểu tượng ":" TFC ",
" số thập phân ": 6,
" trạng thái ":" hoạt động ",
" id ":" 1004117 "

**Comment by Theflashcurrency-TFC** [comment]
Hello Justswap team I want to list TFC token please approve and guide me through the omission process.  We work hard and hard on our project!  thanks!

**Comment by Theflashcurrency-TFC** [comment]
{
   "name": "TheFlashCurrency", #List name
   "logoURI": "https://coin.top/production/upload/logo/1004117.png", #List logo uri
   "timestamp": 1610339529000, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TSgPrApcEfhrsrcyNnKp21cQbup7DEZF3U", #Token address
           "name": "TheFlashCurrency", #Token name
           "symbol": "TFC", #Token symbol
           "decimals": 6, #Token decimals
           "logoURI": "https://coin.top/production/upload/logo/1004117.png" #Token logo uri
         
       }
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by Theflashcurrency-TFC** [comment]
{
    "name": "The Flash Currency",
    "logoURI":
"https://coin.top/production/upload/logo/1004117.png",
    "timestamp": 1623982782000,
    "version": {
        "major": 1,
        "minor": 1,
        "patch": 2
    },
"tokens": [
        {
            "symbol": "USDT",
            "address": "TSgPrApcEfhrsrcyNnKp21cQbup7DEZF3U",
            "chainId": 1,
            "decimals": 6,
            "name": "Tether USD",
            "logoURI": "https://coin.top/production/logo/usdtlogo.png"
        },
        {

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
