### ISSUE TITLE
Add JustList: LuciferTokenList

### ISSUE THREAD

**Issue by project-asuran** [justswaporg/justlists#1505]
https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [*] I understand that this is not the place to request a token listing.
- [*] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [*] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://buylucifer.co.in/documents/lucifertokenlist.json
JustList Name: LuciferTokenList
Link to the official homepage of the JustList manager: https://buylucifer.co.in

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by project-asuran** [comment]
I am unable to find the mistake. Your valuable support will be helpful
