### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by cirous** [justswaporg/justlists#1543]
https://github.com/justswaporg/justlists/happydream.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: happydream
Link to the official homepage of the JustList manager:

**Comment by cirous** [comment]
for using Happy dream token in just swap

**Comment by stevenstc** [comment]
please close this issue as it does not meet the requirements

**Comment by stevenstc** [comment]
not a place to list the tokens

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
