### ISSUE TITLE
Add JustList: Jambo

### ISSUE THREAD

**Issue by jambocrypto** [justswaporg/justlists#1558]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://jambo.digital/jambo.json
JustList Name: Jambo
Link to the official homepage of the JustList manager: https://jambo.digital

**Comment by stevenstc** [comment]
You only have one token is no a list, please close this issue

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
