### ISSUE TITLE
Add JustList: {numsscoin}

### ISSUE THREAD

**Issue by Numsscoin** [justswaporg/justlists#1566]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/numsscoin.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/justswaporg/justlists/numsscoin.justlists.ts
JustList Name: numsscoin
Link to the official homepage of the JustList manager:https://justswap.link/?lang=en-US#/home?utm_source=tronlink

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by Nolove90** [comment]
Crazy ah

Vào BE 2564 thg 7 12, Th 2 lúc 16:58 jeffwami ***@***.***> đã
viết:

**Comment by Numsscoin** [comment]
Hi I want to listvmy coin is called ( numsscoin) in jutlist but i cantHelp me pleaseAlso i want to list my token in justsawp but every time i lost all my tron in my walletPlease help meThanxxxارسال شده از دستگاه Galaxy من
-------- پیام اصلی --------از: jeffwami ***@***.***> تاریخ: ۲۰۲۱/۷/۱۲  ۱۳:۲۸  (GMT+03:30) گیرنده: justswaporg/justlists ***@***.***> گیرنده کپی: Numsscoin ***@***.***>, Author ***@***.***> موضوع Re: [justswaporg/justlists] Add JustList: {numsscoin} (#1566) 
Closed #1566.
