### ISSUE TITLE
添加JustList: cfb

### ISSUE THREAD

**Issue by pmj0812** [justswaporg/justlists#1659]
{
   "name": "cfb", #List名称
   "logoURI": "http://dapp.fbank.space/icon.png", #List logo uri
   "timestamp": 1627462197809, #以毫秒为单位的更新时间
   "tokens": [{
           "chainId": 1, #ChainId,目前为1
           "address": "TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9", #Token地址
           "name": "Future Bank", #Token名称
           "symbol": "FB", #Token符号缩写
           "decimals": 18, #Token小数位数
           "logoURI": "http://dapp.fbank.space/fbtestlogo.png" #Token logo uri
       }
   ],
   "version": { #版本信息
       "major": 1, #主版本号
       "minor": 0, #次版本号
       "patch": 0  #补丁版本号
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
