### ISSUE TITLE
Add JustList: {PiNetwork}

### ISSUE THREAD

**Issue by Pinetworkfoundation** [justswaporg/justlists#1662]
{
"name": "PiNetwork Token",
"logoURI": "https://coin.top/production/upload/logo/TVETRYrRHQuNkyPKTppzPEZ5AqvbdpqaUw.png",
"dấu thời gian": 1610339529000,
"mã thông báo": [{
"chainId": 1,
"address": "TVETRYrRHQuNkyPKTppzPEZ5AqvbdpqaUw",
"name": "Token",
"symbol": "Pi",
"decimals": 7,
 "logoURI": "https://coin.top/production /upload/logo/TVETRYrRHQuNkyPKTppzPEZ5AqvbdpqaUw.png"
},
],
" phiên bản ": {
" major ": 1,
" minor ": 0,
"bản vá ": 0
}
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
