### ISSUE TITLE
lemon token (lt)

### ISSUE THREAD

**Issue by farshiGold** [justswaporg/justlists#1682]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by farshiGold** [comment]
JustList adres: TNY91updfQUD9p9bCSycLD1rFZUA6YqSbs
JustList name : lemon token  (lt)
url: https://www.lemongame.io
contract address:TNY91updfQUD9pCSycLD1rFZUA6YqSbs
 Issuer   : TPYdH69vd9KFenJCoj5GLWN2H8PdCq6u5r
White Paper: 
https://www.lemongame.io/Lemon%20game%20Whit
LemonToken (LT)
Lemon Game is a pass community-based game distribution and trading platform based in Russia. Game developers can develop and launch blockchain games on the Lemon Game.

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
