### ISSUE TITLE
NUBA - Nuba Healthtech

### ISSUE THREAD

**Issue by criptocomunidad** [justswaporg/justlists#1701]
JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

	},
	"tokens": [{
                 "name": "NubaHealthTech",	
        	"symbol": "NUBA",
		"address": "TBNfj8Q2WoDUEYab5bQNPbw9sGnqsc29y9,
		"chainId": 1,
		"decimals": 18,
		"name": "NUBA",
		"logoURI": "https://nubapass.com/wp-content/uploads/2021/04/Recurso-26.png

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
