### ISSUE TITLE
Add JustList: PAX TRC10

### ISSUE THREAD

**Issue by KAMLEGENDZ** [justswaporg/justlists#1702]
{
           "chainId": 1,
           "address": "TUx2bixRHR4TV9ZGNztFzk9nAcEQ2t4Le5",
           "name": "PAX",
           "symbol": "PAX",
           "decimals": 18,
           "logoURI": "https://s2.coinmarketcap.com/static/img/coins/200x200/3330.png"
       }
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
