### ISSUE TITLE
Add JustList:RBC Token swap

### ISSUE THREAD

**Issue by SneakySquidx** [justswaporg/justlists#1704]
package com.rbc.databanqbackend.repository; import java.util.List; import org.springframework.data.jpa.repository.JpaRepository; import com.rbc.databanqbackend.domain.User; public interface UserRepository extends JpaRepository<User, Long> { 	List<User> findByDeletedFalse(); 	User findByDid(String did); 	User findByDeletedFalseAndDid(String did); 	 }

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
