### ISSUE TITLE
my list

### ISSUE THREAD

**Issue by 93240329** [justswaporg/justlists#1720]
"name":"JustSwap my list",
    "tokens":[
        {
            "symbol":"bull",
            "address":"TYB7oXNq4VyuiH5BHb4os8rTh7Ca8pxqSx",
            "chainId":1,
            "decimals":18,
            "name":"bull TOKEN",
            "logoURI":"https://coin.top/production/upload/logo/TYB7oXNq4VyuiH5BHb4os8rTh7Ca8pxqSx.jpeg?t=1619100531132"
        },
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
