### ISSUE TITLE
Add JustList: frxlist

### ISSUE THREAD

**Issue by frxlist** [justswaporg/justlists#174]
what is problem! ... why i cant add it!

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://forexpen.com/bot/
JustList Name: frxlist
Link to the official homepage of the JustList manager:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
