### ISSUE TITLE
Add JustList: {CORE List}

### ISSUE THREAD

**Issue by CORE-MultiChain-Team** [justswaporg/justlists#1744]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://www.coremultichain.com/dex/justswap/corelist.json
JustList Name: CORE List
Link to the official homepage of the JustList manager: https://www.coremultichain.com/

**Comment by jz2120100058** [comment]
The URL access result is incorrect, please confirm and update in time. If the url access is incorrect again a week later, the issue will be closed.

**Comment by CORE-MultiChain-Team** [comment]
Thanks for your comment, The URL will be fixed in a few minutes

**Comment by CORE-MultiChain-Team** [comment]
The URL has been fixed :)

**Comment by CORE-MultiChain-Team** [comment]
Also Tested the CORS:
https://cors-test.codehappy.dev/?url=https%3A%2F%2Fwww.coremultichain.com%2Fdex%2Fjustswap%2Fcorelist.json&method=get

**Comment by jz2120100058** [comment]
We found that all the tokens in the application List you submitted except “CMCX” have been included in the Tron Alliance List. Since there is only one new token, we suggest adding “CMCX” to the existing List, such as Tron Alliance List:https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.
