### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by playandlike14** [justswaporg/justlists#1776]
https://github.com/justswaporg/justlists/example.justlists.ts

**PlayAndLike(PAL) is to create a platform where people can come and entertain themselves with small videos posted by people across the globe and earn the PAL Token. Wrapped PAL token will be used for staking. Anyone can convert the TRC10 PAL token to TRC20 WPAL.**
https://justswap.io/?lang=en-US#/scan/detail/trx/TMWfR1USPf9bQqmQa9ZAh3NapeCY417fGD

JustList URL: https://justswap.io/?lang=en-US#/scan/detail/trx/TMWfR1USPf9bQqmQa9ZAh3NapeCY417fGD
JustList Name: Wrapped PlayAndLike (WPAL)
Link to the official homepage of the JustList manager:https://playandlike.com/

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by hatamiarash7** [comment]
Can you list this token ??? Please check it again
