### ISSUE TITLE
0xb07e0981b39A26B89e95B46abec1532DdbCA2905

### ISSUE THREAD

**Issue by Peiman25800** [justswaporg/justlists#1862]
0xb07e0981b39A26B89e95B46abec1532DdbCA2905

_Originally posted by @Peiman25800 in https://github.com/MicrosoftDocs/AdaptiveCards/issues/411#issuecomment-912213054_

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
