### ISSUE TITLE
 Accept application/json, text/plain, */*Add JustList: {JustList name}

### ISSUE THREAD

**Issue by fublok77** [justswaporg/justlists#1870]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

Accept
application/json, text/plain, */*
https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.accountv2?address=TQT8oMviyRPrgAiD7WTU7ftnAdqQxVQV3a

JustList URL: 
JustList Name: justswap.org'
Link to the official homepage of the JustList manager:{"address":"TQT8oMviyRPrgAiD7WTU7ftnAdqQxVQV3a","cN":0,"hexList":["0a81020a02d44d2208e43b1ee6de5c67cc40d0c8c7fbba2f5ae201080512dd010a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5769746e657373437265617465436f6e747261637412a6010a15419ed9e68858127be10c1d1be5cc0a40735a20b6f1128c0168747470733a2f2f6c6973742e74726f6e6c696e6b2e6f72672f6170692f77616c6c65742f6d756c74692f7472785f7265636f72643f616464726573733d545154386f4d76697952507267416944375754553766746e416471517856515633612673746172743d302673746174653d30266c696d69743d35303030266e6574547970653d6d61696e5f6e657470bbfec3fbba2f"],"tN":0,"type":14}
https://list.tronlink.org/api/wallet/multi/trx_record?address=TQT8oMviyRPrgAiD7WTU7ftnAdqQxVQV3a&start=0&state=0&limit=5000&netType=main_net

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
