### ISSUE TITLE
TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9

### ISSUE THREAD

**Issue by Peiman25800** [justswaporg/justlists#1906]
TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9

_Originally posted by @sadeghzare2580 in https://github.com/justswaporg/justlists/issues/1809#issuecomment-913083719_

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
