### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by uuiiqqbbs** [JustSwapOrg/justlists#1964]
Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://raw.githubusercontent.com/uuiiqqbbs/list/main/besttronalliance.json
JustList Name: WSBCToken
Link to the official homepage of the JustList manager:https://github.com/uuiiqqbbs

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
