### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by wolfscloud-org** [JustSwapOrg/justlists#1992]
{
           "chainId": 1,
           "address": "TK834t3gjG7sCdv8gpLHPnoisb3FLokWs6",
           "name": "WOLFSCLOUD",
           "symbol": "WOLFS",
           "decimals": 6,
           "logoURI": "https://coin.top/production/upload/logo/TK834t3gjG7sCdv8gpLHPnoisb3FLokWs6.png"
       }
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
