### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by lalithanddil** [JustSwapOrg/justlists#2007]
{
   "name": "Direct Income to Lanka", #List name
   "logoURI": "https://coin.top/production/upload/logo/TNk9qqSdn5xTXRzEzfsHZPWXEmgHRSfkxb.png", #List logo uri
   "timestamp": 1610339529000, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TNk9qqSdn5xTXRzEzfsHZPWXEmgHRSfkxb", #Token address
           "name": "Direct Income to Lanka", #Token name
           "symbol": "DIL", #Token symbol
           "decimals": 6, #Token decimals
           "logoURI": "https://coin.top/production/upload/logo/TNk9qqSdn5xTXRzEzfsHZPWXEmgHRSfkxb.png" #Token logo uri
       },
       {
           "chainId": 1,
           "address": "TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT",
           "name": "USDJ",
           "symbol": "USDJ",
           "decimals": 18,
           "logoURI": "https://coin.top/production/logo/usdj.png"
       }
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by lalithanddil** [comment]
what is wrong
