### ISSUE TITLE
Add JustList: {ASB}

### ISSUE THREAD

**Issue by asbazar** [JustSwapOrg/justlists#2008]
https://asbazar.com/asb.json

Checklist
- [*] **I understand that this is not the place to request a token listing.**
- [*] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [*] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

JustList URL must be HTTPS.

JustList URL: https://asbazar.com/asb.json
JustList Name: ASB
Link to the official homepage of the JustList manager:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
