### ISSUE TITLE
添加JustList: Coral List

### ISSUE THREAD

**Issue by Melicrate** [justswaporg/justlists#203]
检查清单
- [x] **我已知晓此issue不是提交token而是提交JustList**
- [x] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [x] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

JustList URL: https://coinral.com/swap/list.json
JustList 名称: Coral List
JustList 提交者的网站或主页: https://coinral.com

**Comment by stevenstc** [comment]
your link does not have a secure https connection and your request will be rejected fix it

**Comment by stevenstc** [comment]
https://coinral.com/swap/list.json
Please correct the protocol, as it is not safe, if you do not do it you will not meet the requirements

**Comment by Joejoe42** [comment]
Gi

**Comment by Momoj60** [comment]
Hi

**Comment by jz2120100058** [comment]
The URL and website cannot be accessed, please confirm and update in time. If the url and website cannot be accessed after one week, the issue will be closed.

**Comment by jz2120100058** [comment]
Sorry, the issue will be closed as the URL and website cannot be accessed.
