### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by oktopus12** [justswaporg/justlists#2045]
"{"total":1.12502735658329E10,"projects":[{"project":"TRX Staking Governance","logo":"https://coin.top/production/upload/logo/Staking.png","type":"Governance","vip":"0","locked":3085315574.81,"url":"https://tronscan.org/#/data/charts/OverallFreezingRate","gain":0.0031},{"project":"JustLend","logo":"https://coin.top/production/upload/logo/justlend.png","type":"Lending","vip":"1","locked":2031283506.08,"url":"https://justlend.justnetwork.io/#/home","gain":0.0437},{"project":"JustStable","logo":"https://coin.top/production/upload/logo/juststable.png","type":"Stablecoin,Lending","vip":"1","locked":1746537962.32,"url":"https://juststable.tronscan.org/#/login\n","gain":0.0150},{"project":"Just Cryptos","logo":"https://coin.top/production/upload/logo/justcryptos.png","type":"Cross Chain","vip":"0","locked":1638697376.17,"url":"https://justnetwork.io/token","gain":0.0805},{"project":"JustSwap","logo":"https://coin.top/production/upload/logo/justswap.png","type":"DEX,AMM,Farm","vip":"1","locked":1431391862.20,"url":"https://justswap.link/?lang=zh-CN#/home","gain":0.0186},{"project":"SUN.io","logo":"https://coin.top/production/upload/logo/sun10.png","type":"Stablecoin,DEX,Farm","locked":1317047284.25,"url":"https://sun.io/#/home","gain":-0.0014}]}"
 https://apilist.tronscan.org/api/defiTvl#:~:text=%7B%22total%22%3A1.12502735658329E10%2C%22projects,home%22%2C%22gain%22%3A-0.0014%7D%5D%7D

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
