### ISSUE TITLE
I will remove auto harden function. Users will be able to use the HD path as is. I'll add the parameter &version=2 to avoid confusion for existing users.

### ISSUE THREAD

**Issue by Hjordaan2002** [justswaporg/justlists#2065]
I will remove auto harden function. Users will be able to use the HD path as is. I'll add the parameter &version=2 to avoid confusion for existing users.
Version param: https://github.com/cosmostation/keystation/blob/dev/service/service.go#L68
Auto harden: https://github.com/cosmostation/keystation/blob/dev/www/js/import.js#L134
Auto harden: https://github.com/cosmostation/keystation/blob/dev/www/js/pin.js#L143

_Originally posted by @Booyoun-Kim in https://github.com/cosmostation/keystation/issues/7#issuecomment-700391315_

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
