### ISSUE TITLE
Add JustList: RDMlist

### ISSUE THREAD

**Issue by Jensyr13** [justswaporg/justlists#2112]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/Jensyr13/RDMToken/blob/main/RDMList.JSON
JustList Name: RDMlist
Link to the official homepage of the JustList manager: https://github.com/Jensyr13/RDMToken

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by Jensyr13** [comment]
Where can I find out how to do it correct?ThanksEl 26 oct. 2021 11:30 p. m., jeffwami ***@***.***> escribió:
Sorry, your issue will be closed as you did not submit your information in the correct format.
