### ISSUE TITLE
Add JustList: CeTaStore Token

### ISSUE THREAD

**Issue by cetastore** [justswaporg/justlists#2114]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL:  https://drive.google.com/file/d/1F-SCwWO7h_rzwEaKCqTX_st93aXrqBob/view?usp=sharing
JustList Name: CeTaStore Token JustList
Link to the official homepage of the JustList manager:

**Comment by l148** [comment]
MERIT合约地址公开http://t.cn/A6cmLh5Q                                                                                   MERIT币目前支持TP钱包   比特派钱包   BiTKeep钱包   麦子钱包  HyperPay钱包  同时转账，转账需要能量和宽带。需要在社区群内发你的收币地址。钱包需要保管好自己的助记词。币种添加好合约地址。我们欢迎新成员加入转账测试。MERIT币的成员也是自由自愿方式加入，人员自由创建地址   MERIT社区合约地址公开性。微信如果打不开可以复制到浏览器打开复制合约地址。新建电报群http://t.cn/A6VSfNjC  新建微博粉丝群http://t.cn/A67xwqUI     电报群http://t.cn/A6fGUML3     MERIT 社区
http://t.cn/A6IbzQNS            点击链接加入群聊【MERIT社区群】：https://jq.qq.com/?_wv=1027&k=Mlk5F1e2

**Comment by l148** [comment]
![Uploading Screenshot_20211028_023311.jpg…]()

**Comment by l148** [comment]
![Uploading Screenshot_20211028_023454.jpg…]()

**Comment by l148** [comment]
![Uploading Screenshot_20211028_023254.jpg…]()

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
