### ISSUE TITLE
Add JustList: {Community Inu Token}

### ISSUE THREAD

**Issue by addijee** [JustSwapOrg/justlists#2188]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://communityinu.org/jason/
JustList Name: Community Inu Token
Link to the official homepage of the JustList manager: https://communityinu.org/

**Comment by addijee** [comment]
Dear Jeffwami 

Now i upload all these details which are required from your side , i want to add my Community token at Sun Swap kindly approve my request and guide me the further detail 

Regards

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by addijee** [comment]
What is the right way to submit any information ?? Can you explain it 
I already attempt many times now i give you jason file and all the stuff which you required but your issue is same.
Can you plz guide me that what is the right way to submit my information ???
