### ISSUE TITLE
What is the right way to submit any information ?? Can you explain it

### ISSUE THREAD

**Issue by addijee** [JustSwapOrg/justlists#2192]
What is the right way to submit any information ?? Can you explain it 
I already attempt many times now i give you jason file and all the stuff which you required but your issue is same.
Can you plz guide me that what is the right way to submit my information ???

_Originally posted by @addijee in https://github.com/justswaporg/justlists/issues/2188#issuecomment-966139931_

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
