### ISSUE TITLE
Add JustList: REAL LOVE Token

### ISSUE THREAD

**Issue by dj68104** [JustSwapOrg/justlists#2196]
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://www.linkpicture.com/q/Tokenkieron-2-200.png
JustList Name: REAL LOVE
Link to the official homepage of the JustList manager: https://thefirst.matrixtoken.agency/

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by dj68104** [comment]
Jeff what is the correct format? What did I get wrong?
