### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by kirkorof** [justswaporg/justlists#22]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: ever
Link to the official homepage of the JustList manager:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
