### ISSUE TITLE
JustList: {PDT}

### ISSUE THREAD

**Issue by Parall901** [JustSwapOrg/justlists#2200]
{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"PDT",
            "address":"TFpqLdyzdSnfEGMrZR4d3R3gb5Nt2jDgmz",
            "chainId":1,
            "decimals":6,
            "name":"Parallel Universe Token",
            "logoURI":"https://coin.top/production/upload/logo/TFpqLdyzdSnfEGMrZR4d3R3gb5Nt2jDgmz.png"
        },
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1636851377000
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
