### ISSUE TITLE
Add JustList: {Funex}

### ISSUE THREAD

**Issue by funexcoin** [JustSwapOrg/justlists#2340]
https://github.com/funexcoin/FunexSol/tree/master/TRC20

JustList URL: https://sunswap.com/#/scan/token/detail/TMYBRDphyekK3JR31RuthpUx6N8Qcj6Wao
JustList Name:  Funex
Link to the official homepage of the JustList manager: https://funexcoin.com/

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
