### ISSUE TITLE
Add JustList: {boscoin}

### ISSUE THREAD

**Issue by Tyler-Franklin** [JustSwapOrg/justlists#2387]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

Please provide the following information for your token.
JustList URL must be HTTPS.

JustList URL: https://tyler-franklin.github.io/metadata/json/token/bos/boscoin.json
JustList Name: boscoin
Link to the official homepage of the JustList manager:https://punkshequ.com/

**Comment by jz2120100058** [comment]
We found that the tokens in the application List you submitted are already included in the [Tron Alliance List](https://justlists.just.network/#/detail?uri=https://list.tronalliance.cc/tronalliance.json), so we recommend you to use the Tron Alliance List.
