### ISSUE TITLE
Add JustList: {JustList.surachai0}

### ISSUE THREAD

**Issue by surachai0** [JustSwapOrg/justlists#2412]

**Comment by surachai0** [comment]
จะลบได้อย่างไรวะ

**Comment by surachai0** [comment]
> 
> 
> 
> https://github.com/justswaporg/justlists/example.justlists.ts
> 
> Checklist
> 
> * [x]  **I understand that this is not the place to request a token listing.**
> * [x]  I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
> * [x]  I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.
> 
> **Please provide the following information for your token.** JustList URL must be HTTPS.
> 
> JustList URL: JustList Name: Link to the official homepage of t

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
