### ISSUE TITLE
Add JustList: {PunkShequ}

### ISSUE THREAD

**Issue by Tyler-Franklin** [JustSwapOrg/justlists#2420]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**

JustList URL: https://tyler-franklin.github.io/metadata/json/token/dak/dakcoin.json
JustList Name:  PunkShequ
Link to the official homepage of the JustList manager: https://punkshequ.com

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.
