### ISSUE TITLE
jWBTT to BTT on SunSwap  issue

### ISSUE THREAD

**Issue by Blueberryjam51** [justswaporg/justlists#2447]
Hi all,

I write this hoping I didn't mess up. 

I have or should I say had some wrapped BTT (WBTT) on JustLend. I wanted to swap them to BTT and used SunSwap.

SunSwap saw my jWBTT on my wallet and allowed me to swap but there is no sign of them in my wallet, I checked Transcan and can see that it was a 'success'.

The WBTT are not on my JustLend account so they have gone somewhere.

Does anyone know if I should be looking in another place rather than my wallet are they held temporarily somewhere or is this wishful thinking.

Thanks for all comments

YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
