### ISSUE TITLE
mbhu.justlists.ts

### ISSUE THREAD

**Issue by wangchenglin** [justswaporg/justlists#2452]
{
    "name":"JustSwap MBHU List",
    "tokens":[
        {
            "symbol":"MBHU",
            "address":"TNvwYBR9FKznJ4n5Mt4jamx8Lbxh4caCtd",
            "chainId":1,
            "decimals":18,
            "name":"mbhu",
            "logoURI":"https://www.mbhu.info/bhu/img/logo.png"
        },
       
        {
            "symbol":"USDT",
            "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        }
    ],
    "logoURI":"https://www.mbhu.info/bhu/img/logo.png",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1642483129000
}

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.Please resubmit
