### ISSUE TITLE
JustList: {mbhu}

### ISSUE THREAD

**Issue by wangchenglin** [justswaporg/justlists#2455]
JustList URL: https://www.mbhu.info
JustList 名称: mbhu
JustList 提交者的网站或主页: https://github.com/wangchenglin/justlists/blob/main/mbhu.justlists.ts

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.
