### ISSUE TITLE
Add JustList: MBHU Token List

### ISSUE THREAD

**Issue by wangchenglin** [justswaporg/justlists#2456]
检查清单
- [x] **我已知晓此issue不是提交token而是提交JustList**
- [x] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [x] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

JustList URL: https://www.mbhu.info/justlist.json
JustList 名称: MBHU Token List
JustList 提交者的网站或主页:https://www.mbhu.info

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
The URL (https://github.com/justswaporg/justlists/blob/main/example.justlists.ts)in the example just tells the list the standard format. The final URL submitted please refer to https://list.tronalliance.cc/tronalliance.json.

**Comment by jz2120100058** [comment]
https://user-images.githubusercontent.com/20548311/149891669-975c86e0-7020-4953-8a3e-e61d4551b75a.png
The list can not be added. Please confirm and handle it。

**Comment by jz2120100058** [comment]
Thanks for reaching out.The last problem has been solved.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by surachai0** [comment]
https://www.surachai/justlist.json

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as the issue has not been replied for more than one month.Please submit again if you would like to apply for a new list.
Finally, thank you again for your application.I hope you are having a great day.
