### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by byrdbitch1** [justswaporg/justlists#2463]
Current Statistics
This page shows the current status of the entire project, including how many users are there and the total amount deposited and withdrawn so far.

Current Status: ✅ Paying
Withdrawal Status: ✅ Automatic

👥 Total Users
1506 users registered 

📥 Total Investments (USD)
$331,777.29USD deposited 

📤 Total Withdrawn (USD)
$132,676.62USD withdrawnhttps://github.com/justswaporg/justlists/blob/main/example.justlists.tshttps://etherscan.io/address/0x2ba592F78dB6436527729929AAf6c908497cB200#code#L1

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close.
