### ISSUE TITLE
Add JustList: {DZIRE TOKEN}

### ISSUE THREAD

**Issue by Dreams961** [justswaporg/justlists#2482]
"symbol":"DZR",
            "address":"TEZdC6tv9LqN5DabUTmpiPTnYx5jLGtq2E",
            "chainId":1,
            "decimals":18,
            "name":"DZIRE TOKEN",

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.Please resubmit.
