### ISSUE TITLE
Add JustList: {DZIRE TOKEN}

### ISSUE THREAD

**Issue by Dreams961** [justswaporg/justlists#2485]
"symbol":"DZR",
"address":"TEZdC6tv9LqN5DabUTmpiPTnYx5jLGtq2E",
"chainId":1,
"decimals":6,
"name":"DZIRE TOKEN",

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

**Comment by jz2120100058** [comment]
Thanks for reaching out.
You did not submit your information in the correct format.Please resubmit.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as  you have not resubmitted your information in the correct format for more than a week.
