### ISSUE TITLE
DCIPJustList: {DCIPJustList name}

### ISSUE THREAD

**Issue by tcllong** [justswaporg/justlists#2493]
{
 "name": "DCIPJustList", #List名称
 "logoURI": "https://coin.top/production/logo/usdj.png", #List logo uri
 "timestamp": 1610339529000, #以毫秒为单位的更新时间
 "tokens": [{
 "chainId": 1, #ChainId,目前为1
 "address": "TCRXsDPdFhs8roNkiBFKrb9FPZx8iTB17E", #Token地址
 "name": "DCIP", #Token名称
 "symbol": "DCIP", #Token符号缩写
 "decimals": 18, #Token小数位数
 "logoURI": "https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png" #Token logo uri
 },
 {
 "chainId": 1,
 "address": "TCRXsDPdFhs8roNkiBFKrb9FPZx8iTB17E",
 "name": "DCIP",
 "symbol": "DCIP",
 "decimals": 18,
 "logoURI": "https://coin.top/production/logo/usdj.png"
 }
 ],
 "version": { #版本信息
 "major": 1, #主版本号
 "minor": 0, #次版本号
 "patch": 0 #补丁版本号
 }
}

**Comment by jz2120100058** [comment]
Thanks for reaching out.
You did not submit your information in the correct format.Please resubmit.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as  you have not resubmitted your information in the correct format for more than a week.
