### ISSUE TITLE
Keystore

### ISSUE THREAD

**Issue by Mehrnazibi** [justswaporg/justlists#2498]
{"address":"36e4f28c68731e4375772c7284d50e0e3bc375ba","id":"086a8afe-b98c-44ce-8bd7-a09c8efad239","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"210cbeea77825e5b019467a570a5e261"},"ciphertext":"a12362ce28c728287a7d4a010d22b4888fb082239137f090877b05afc1d2f9a1","kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"68ea1fbfdfd98634136e27ce719d49b97a908de3575e75713949b01defbf67c8"},"mac":"f430ed5e973b6bc97c71df97ef01ff491315d0e46629d5e15500bf1963f1931b"}}

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.Please resubmit.
