### ISSUE TITLE
添加JustList: {BBC}

### ISSUE THREAD

**Issue by shange168** [justswaporg/justlists#2508]
{
            "symbol":"BBC",
            "address":"TQ41xtxodRaTqFdtxbU2VWZammyPXBC5me",
            "chainId":1,
            "decimals":6,
            "name":"BBCToken",
            "logoURI":"https://trx.cx/static/user/images/tgf$.cd995ec1.png"
        },

**Comment by jz2120100058** [comment]
Thanks for reaching out.
You did not submit your information in the correct format.Please resubmit.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as  you have not resubmitted your information in the correct format for more than a week.
