### ISSUE TITLE
Add JustList: {1337Tpunk.com List}

### ISSUE THREAD

**Issue by 1337Tpunk** [justswaporg/justlists#2518]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://1337tpunk.com/example.justlists.ts
JustList Name: 1337Tpunk.com List
Link to the official homepage of the JustList manager: [1337Tpunk.com](https://1337tpunk.com/)

**Comment by 1337Tpunk** [comment]
[example.justlists.ts.txt](https://github.com/justswaporg/justlists/files/8036638/example.justlists.ts.txt)

Please disregard the previous file uploads.

Let me know what needs to be modified please because it validates but does not work..

**Comment by 1337Tpunk** [comment]
Let me know what needs to be modified please because it validates but does not work..
[example.justlists.ts.txt](https://github.com/justswaporg/justlists/files/8036679/example.justlists.ts.txt)
[example.sunlists.ts.txt](https://github.com/justswaporg/justlists/files/8036680/example.sunlists.ts.txt)

**Comment by 1337Tpunk** [comment]
https://1337tpunk.com/1337Tpunk.json

http://list.1337tpunk.com/1337Tpunk.json

**Comment by jz2120100058** [comment]
Thanks for your application.
Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
Please share more info to us at: [support@sunswap.com](mailto:support@sunswap.com)
It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
Thanks

**Comment by 1337Tpunk** [comment]
Hi Jerry,

Thank you very much for your previous reply, I hope you are having a great
day.
.
1337Tpunk.com is a project that aims to promote Art and NFTs
<https://1337tpunk.com/nfts/> by helping Artists
<https://1337tpunk.com/1337-nft-artists/> find a Digital Marketing platform
where their work can be displayed and promoted.

It also exists to promote crypto technologies on Tron.and the use of TRX
and many other Tokens on the Tron Network.

Here is some of the information requested in the previous email:


Website: https://1337tpunk.com/

Telegram: https://t.me/I337Tpunk

Twitter: https://twitter.com/1337Tpunk

Medium: ***@***.***

Instagram: https://www.instagram.com/1337Tpunk

Kraftly NFTs:
https://kraftly.io/author/TNEPGjhvyooVnhgxsf4hZEDZ634yRKMrgJ?tab=collection

NFTone: https://nftone.net/user/TNEPGjhvyooVnhgxsf4hZEDZ634yRKMrgJ

USWAP: https://uswap.me/market/author/691

Fans Forever: https://app.fansforever.io/profile/1337%20Tpunk


Thank you for letting me know when the Token List
<https://1337tpunk.com/1337Tpunk.json> can be added (it will be well
maintained in the future too).

https://1337tpunk.com/1337Tpunk.json


Kind Regards,

1337Tpunk
1337tpunk.com




jerry ***@***.***> escreveu no dia quinta, 10/02/2022 à(s)
06:32:

**Comment by jz2120100058** [comment]
Thanks for your application, I hope you are having a great day.
We are reviewing it. Because the Token List addition review is very strict, there is a waiting period.

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153555719-7f8d617c-48fa-4477-b088-6b28447f508e.png)
Some token addresses are wrong, please fix them.

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153558741-098b239e-4dda-4f5e-9bba-d7fcbf4e8cd7.png)
![image](https://user-images.githubusercontent.com/20548311/153558850-cfefb0e3-b3a8-4e75-8783-784487a79b85.png)
please find and fix them.

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153560144-2d0a70ea-ccf1-4940-813c-d56750b1a05b.png)
"EXON" and "TURU" token cannot find in SunSwap.

**Comment by 1337Tpunk** [comment]
Hello Jerry,

Thank you very much for your reply.

TERC - TERC Pro
https://tronscan.io/#/token/1003075

This token shows a different address system with a short number.
What should be used instead?

Also:

TGCD
https://tronscan.io/#/token/1003133

This token shows a different address system with a short number.
What should be used instead?

TGCT
https://tronscan.io/#/token/1002664

PLEASE EXCUSE THE ERROR. IT HAS BEEN CORRECTED TO SHOW 1002664

EXON & TURU

I have removed them from the list.

Please let me know what I should do next.

The most recent version is here:

https://1337tpunk.com/1337Tpunk.json

Thank you for your help Jerry, have a great day.

Kind Regards,

1337Tpunk

1337Tpunk.com


.


jerry ***@***.***> escreveu no dia sexta, 11/02/2022 à(s)
07:59:

**Comment by 1337Tpunk** [comment]
Hello again Jerry, I removed those problematic tokens from the list.

Here is the updated list at the link:

https://1337tpunk.com/1337Tpunk.json









{
    "name":"1337Tpunk.com List",
   "logoURI": "https://1337tpunk.com/wp-content/uploads/1337punktron.png",
   "timestamp": 1610339529000,
    "version": {
        "major": 1,
        "minor": 0,
        "patch": 0
    },
    "tokens": [
              {
         "symbol":"USDT",
         "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
         "chainId":1,
         "decimals":18,
         "name":"USDT",
         "logoURI":"
https://coin.top/production/logo/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t.png"
      },
      {
         "symbol":"JST",
         "address":"TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9",
         "chainId":1,
         "decimals":18,
         "name":"JUST GOV v1.0",
         "logoURI":"https://coin.top/production/logo/just_icon.png"
      },
      {
         "symbol":"SUN",
         "address":"TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S",
         "chainId":1,
         "decimals":18,
         "name":"SUN",
         "logoURI":"
https://coin.top/production/logo/TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S.png"
      },
      {
         "symbol":"BTT",
         "address":"TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4",
         "chainId":1,
         "decimals":18,
         "name":"BitTorrent",
         "logoURI":"https://coin.top/production/logo/1002000.png"
      },
      {
         "symbol":"NFT",
         "address":"TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq",
         "chainId":1,
         "decimals":6,
         "name":"APENFT",
         "logoURI":"
https://coin.top/production/upload/logo/TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq.png
"
      },
      {
         "symbol":"WIN",
         "address":"TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7",
         "chainId":1,
         "decimals":6,
         "name":"WIN",
         "logoURI":"https://coin.top/profile_images/JKtJTydD_400x400.jpg"
      },
      {
         "symbol":"KLV",
         "address":"TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS",
         "chainId":1,
         "decimals":6,
         "name":"KLV",
         "logoURI":"
https://coin.top/profile_images/TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS.png"
      },
      {
         "symbol":"DVK",
         "address":"TKk6DLX1xWRKHjDhHfdyQKefnP1WUppEXB",
         "chainId":1,
         "decimals":6,
         "name":"Devikins",
         "logoURI":"
https://coin.top/profile_images/TKk6DLX1xWRKHjDhHfdyQKefnP1WUppEXB.png"
      },
      {
         "symbol":"KFI",
         "address":"TS2oVhqVNh1asf5X6wcdojScUMBg8on726",
         "chainId":1,
         "decimals":6,
         "name":"KleverFinance",
         "logoURI":"
https://coin.top/profile_images/TS2oVhqVNh1asf5X6wcdojScUMBg8on726.png"
      },
      {
         "symbol":"UME",
         "address":"TRkuKAxmWZ4G74MvZnFpoosQZsfvtNpmwH",
         "chainId":1,
         "decimals":8,
         "name":"UME",
         "logoURI":"
https://coin.top/profile_images/TRkuKAxmWZ4G74MvZnFpoosQZsfvtNpmwH.png"
      },
      {
         "symbol":"EFT",
         "address":"TG3XANY34mpabHM2DNc5ajhjMJVUQU741Y",
         "chainId":1,
         "decimals":8,
         "name":"EFT Finance",
         "logoURI":"
https://coin.top/profile_images/TG3XANY34mpabHM2DNc5ajhjMJVUQU741Y.png"
      },
      {
         "symbol":"KODX",
         "address":"TTUwzoZAK6rpDjpSh8B2XFTnxGfbMLHJaq",
         "chainId":1,
         "decimals":6,
         "name":"KODX",
         "logoURI":"
https://coin.top/production/logo/TTUwzoZAK6rpDjpSh8B2XFTnxGfbMLHJaq.jpg"
      },
      {
         "symbol":"YFX",
         "address":"TAP7qf8Ao26ZAKYS5E6SGozUNoSLvBHsGa",
         "chainId":1,
         "decimals":18,
         "name":"YFX",
         "logoURI":"
https://coin.top/profile_images/TTAP7qf8Ao26ZAKYS5E6SGozUNoSLvBHsGa.png"
      },
      {
         "symbol":"JM",
         "address":"TT8VkSkW6igkiRsV5WiJgLrsbVwY5bLLjA",
         "chainId":1,
         "decimals":8,
         "name":"Just Money",
         "logoURI":"
https://coin.top/profile_images/TT8VkSkW6igkiRsV5WiJgLrsbVwY5bLLjA.png"
      },
      {
         "symbol":"Safe Money",
         "address":"TNBrVEzuVYbNbGF2ua3ivSX5Y5V9N4xhax",
         "chainId":1,
         "decimals":8,
         "name":"Safe Money",
         "logoURI":"
https://coin.top/profile_images/TNBrVEzuVYbNbGF2ua3ivSX5Y5V9N4xhax.png"
      },
      {
         "symbol":"CNS",
         "address":"TMJWuBDvwvcm6QUWXDaC6GqTyq3FgEmWEt",
         "chainId":1,
         "decimals":8,
         "name":"Centric Cash",
         "logoURI":"
https://coin.top/profile_images/TMJWuBDvwvcm6QUWXDaC6GqTyq3FgEmWEt.png"
      },
      {
         "symbol":"CNR",
         "address":"TYLrbh1pVcx95bop33XQ1iYdh7r3ogEQ8Q",
         "chainId":1,
         "decimals":8,
         "name":"Centric Rise",
         "logoURI":"
https://coin.top/profile_images/TYLrbh1pVcx95bop33XQ1iYdh7r3ogEQ8Q.png"
      },
      {
         "symbol":"BNKR",
         "address":"TNo59Khpq46FGf4sD7XSWYFNfYfbc8CqNK",
         "chainId":1,
         "decimals":6,
         "name":"Bankroll Token",
         "logoURI":"
https://coin.top/profile_images/TNo59Khpq46FGf4sD7XSWYFNfYfbc8CqNK.png"
      },
      {
         "symbol":"BNKRX",
         "address":"TKSLNVrDjb7xCiAySZvjXB9SxxVFieZA7C",
         "chainId":1,
         "decimals":6,
         "name":"Bankroll Extended Token",
         "logoURI":"
https://coin.top/profile_images/TKSLNVrDjb7xCiAySZvjXB9SxxVFieZA7C.png"
      },
      {
         "symbol":"HT",
         "address":"TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h",
         "chainId":1,
         "decimals":18,
         "name":"HuobiToken",
         "logoURI":"
https://coin.top/production/logo/TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h.png"
      },
      {
         "symbol":"UP",
         "address":"TJ93jQZibdB3sriHYb5nNwjgkPPAcFR7ty",
         "chainId":1,
         "decimals":6,
         "name":"Social Swap",
         "logoURI":"
https://coin.top/production/logo/TJ93jQZibdB3sriHYb5nNwjgkPPAcFR7ty.jpg"
      },
      {
         "symbol":"CREED",
         "address":"TM2fhs1CFiS696VW13s3oBuDdPazCEGcfJ",
         "chainId":1,
         "decimals":6,
         "name":"Creed Finance",
         "logoURI":"
https://coin.top/production/logo/TM2fhs1CFiS696VW13s3oBuDdPazCEGcfJ.jpg"
      },
      {
         "symbol":"CREEDX",
         "address":"TQSC8P2nLsawUZHF6iMAD6KPH8HdJXFWYi",
         "chainId":1,
         "decimals":6,
         "name":"CREEDX",
         "logoURI":"
https://coin.top/production/logo/TQSC8P2nLsawUZHF6iMAD6KPH8HdJXFWYi.jpg"
      },
      {
         "symbol":"TOFU",
         "address":"TTgnhmov3ezeUGxnfDdjvDt4WhNXDUD3bT",
         "chainId":1,
         "decimals":6,
         "name":"TofuDeFi",
         "logoURI":"
https://coin.top/production/logo/TTgnhmov3ezeUGxnfDdjvDt4WhNXDUD3bT.jpg"
      },
      {
         "symbol":"PNUT",
         "address":"TPZddNpQJHu8UtKPY1PYDBv2J5p5QpJ6XW",
         "chainId":1,
         "decimals":6,
         "name":"PNUT",
         "logoURI":"
https://coin.top/production/logo/TPZddNpQJHu8UtKPY1PYDBv2J5p5QpJ6XW.jpg"
      },
      {
         "symbol":"RENEC",
         "address":"THdCXFZJbf4yUgBRDC4EpXrq8E13xEd7yN",
         "chainId":1,
         "decimals":18,
         "name":"RENEC",
         "logoURI":"
https://coin.top/production/logo/THdCXFZJbf4yUgBRDC4EpXrq8E13xEd7yN.jpg"
      },
      {
         "symbol":"XDV",
         "address":"TGyZUWrL97mmmYJwrC7ZCLVrhbzvHmmWPL",
         "chainId":1,
         "decimals":6,
         "name":"Divvy",
         "logoURI":"
https://coin.top/production/logo/TGyZUWrL97mmmYJwrC7ZCLVrhbzvHmmWPL.jpg"
      },
      {
         "symbol":"LDA",
         "address":"TNP1D18nJCqQHhv4i38qiNtUUuL5VyNoC1",
         "chainId":1,
         "decimals":6,
         "name":"Lion Digital",
         "logoURI":"
https://coin.top/production/logo/TNP1D18nJCqQHhv4i38qiNtUUuL5VyNoC1.jpg"
      },
      {
         "symbol":"NOLE",
         "address":"TPt8DTDBZYfJ9fuyRjdWJr4PP68tRfptLG",
         "chainId":1,
         "decimals":6,
         "name":"Nolecoin",
         "logoURI":"
https://coin.top/production/logo/TPt8DTDBZYfJ9fuyRjdWJr4PP68tRfptLG.jpg"
      },
      {
         "symbol":"AMSK",
         "address":"1001699",
         "chainId":1,
         "decimals":0,
         "name":"AMSK",
         "logoURI":"https://coin.top/production/logo/1001699.jpg"
      },
      {
         "symbol":"FAT",
         "address":"1002939",
         "chainId":1,
         "decimals":6,
         "name":"TRONFamily",
         "logoURI":"https://coin.top/production/logo/1002939.jpg"
      },
      {
         "symbol":"SST",
         "address":"TBLQs7LqUYAgzYirNtaiX3ixnCKnhrVVCe",
         "chainId":1,
         "decimals":8,
         "name":"Social Swap",
         "logoURI":"
https://coin.top/production/logo/TBLQs7LqUYAgzYirNtaiX3ixnCKnhrVVCe.jpg"
      },
      {
         "symbol":"SOUL",
         "address":"THXm85dwyCSTNPq8h1JDPth2vuTcwtXyBb",
         "chainId":1,
         "decimals":6,
         "name":"Soul",
         "logoURI":"
https://coin.top/production/logo/THXm85dwyCSTNPq8h1JDPth2vuTcwtXyBb.jpg"
      },
      {
         "symbol":"SCC",
         "address":"1002670",
         "chainId":1,
         "decimals":6,
         "name":"SCC",
         "logoURI":"https://coin.top/production/logo/1002670.jpg"
      },
      {
         "symbol":"BTZC",
         "address":"1002413",
         "chainId":1,
         "decimals":6,
         "name":"BTZC",
         "logoURI":"https://coin.top/production/logo/1002413.jpg"
      },
      {
         "symbol":"ZLF",
         "address":"TXoPCbHtWTerfiNjFBpJdMQqQJoXoT87pq",
         "chainId":1,
         "decimals":6,
         "name":"ZillonLifePro",
         "logoURI":"
https://coin.top/production/logo/TXoPCbHtWTerfiNjFBpJdMQqQJoXoT87pq.jpg"
      },
      {
         "symbol":"VSN",
         "address":"1003159",
         "chainId":1,
         "decimals":6,
         "name":"Vision",
         "logoURI":"https://coin.top/production/logo/1003159.jpg"
      },
      {
         "symbol":"DEC",
         "address":"1002361",
         "chainId":1,
         "decimals":6,
         "name":"Dark Energy Crystals",
         "logoURI":"https://coin.top/production/logo/1002361.jpg"
      },
      {
         "symbol":"HORA",
         "address":"TNjt5fShPVJ4YpsLuU4THuBbg58g2bZoLk",
         "chainId":1,
         "decimals":6,
         "name":"HORA",
         "logoURI":"
https://coin.top/production/logo/TNjt5fShPVJ4YpsLuU4THuBbg58g2bZoLk.jpg"
      },
      {
         "symbol":"LUMI",
         "address":"TDBNKiYQ8yfJtT5MDP3byu7f1npJuG2DBN",
         "chainId":1,
         "decimals":6,
         "name":"Lumi",
         "logoURI":"
https://coin.top/production/logo/TDBNKiYQ8yfJtT5MDP3byu7f1npJuG2DBN.jpg"
      },
      {
         "symbol":"LUME",
         "address":"TNvgF3Sj2oHKdRGypewWG77NskUvNPoJdj",
         "chainId":1,
         "decimals":8,
         "name":"Lume",
         "logoURI":"
https://coin.top/production/logo/TNvgF3Sj2oHKdRGypewWG77NskUvNPoJdj.jpg"
      },
      {
         "symbol":"PLAT",
         "address":"TG37mUxRUaH1E8DWSrrmoQ79BnZn1yHztb",
         "chainId":1,
         "decimals":6,
         "name":"PLAT",
         "logoURI":"
https://coin.top/production/logo/TG37mUxRUaH1E8DWSrrmoQ79BnZn1yHztb.png"
      },
      {
         "symbol":"MILK",
         "address":"TYaAqxSMub4VSqZFczKDk6NzQp9N9Mcik2",
         "chainId":1,
         "decimals":6,
         "name":"Milk",
         "logoURI":"
https://coin.top/production/logo/TYaAqxSMub4VSqZFczKDk6NzQp9N9Mcik2.jpg"
      },
      {
         "symbol":"DICE",
         "address":"TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd",
         "chainId":1,
         "decimals":6,
         "name":"TRONbetDice",
         "logoURI":"
https://coin.top/production/logo/TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd.jpg"
      },
      {
         "symbol":"PLAY",
         "address":"TYbSzw3PqBWohc4DdyzFDJMd1hWeNN6FkB",
         "chainId":1,
         "decimals":6,
         "name":"PLAY",
         "logoURI":"
https://coin.top/production/logo/TYbSzw3PqBWohc4DdyzFDJMd1hWeNN6FkB.jpg"
      },
      {
         "symbol":"PRIMO",
         "address":"TPbbHx2ztzYoJS12S4BkyhNjRBH9i7539r",
         "chainId":1,
         "decimals":6,
         "name":"PRIMO",
         "logoURI":"
https://coin.top/production/logo/TPbbHx2ztzYoJS12S4BkyhNjRBH9i7539r.jpg"
      },
      {
         "symbol":"TNT",
         "address":"TL33cN6t22RcKyqPKkb14iVrPHDFaFMH7t",
         "chainId":1,
         "decimals":6,
         "name":"Tninja",
         "logoURI":"
https://coin.top/production/logo/TXoPCbHtWTerfiNjFBpJdMQqQJoXoT87pq.jpg"
      },
      {
         "symbol":"BBT",
         "address":"TGyZUWrL97mmmYJwrC7ZCLVrhbzvHmmWPL",
         "chainId":1,
         "decimals":8,
         "name":"Baby Turu",
         "logoURI":"
https://coin.top/production/logo/TGyZUWrL97mmmYJwrC7ZCLVrhbzvHmmWPL.jpg"
      },
      {
         "symbol":"KTY",
         "address":"TTroZqb95vmsw4kppupQ8tVEzkNDDP2bcG",
         "chainId":1,
         "decimals":6,
         "name":"Kraftly",
         "logoURI":"
https://coin.top/production/logo/TTroZqb95vmsw4kppupQ8tVEzkNDDP2bcG.jpg"
      },
      {
         "symbol":"BTC",
         "address":"TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
         "chainId":1,
         "decimals":8,
         "name":"Bitcoin",
         "logoURI":"
https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
      },
      {
         "symbol":"ETH",
         "address":"THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF",
         "chainId":1,
         "decimals":18,
         "name":"Ethereum",
         "logoURI":"
https://coin.top/production/logo/THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF.png"
      },
      {
         "symbol":"DOGE",
         "address":"THbVQp8kMjStKNnf2iCY6NEzThKMK5aBHg",
         "chainId":1,
         "decimals":8,
         "name":"Dogecoin",
         "logoURI":"
https://coin.top/production/logo/THbVQp8kMjStKNnf2iCY6NEzThKMK5aBHg.png"
      },
      {
         "symbol":"LTC",
         "address":"TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd",
         "chainId":1,
         "decimals":8,
         "name":"Litecoin",
         "logoURI":"
https://coin.top/production/logo/TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd.png"

      }
    ]
}







1337 Tpunk ***@***.***> escreveu no dia sexta, 11/02/2022 à(s)
12:58:

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153793316-9535f25e-216b-441f-8ce2-c238a0508994.png)

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153793452-af418f30-f62b-4f15-99cc-d216f1ee37bb.png)

**Comment by jz2120100058** [comment]
Thanks for your application.

**Comment by jz2120100058** [comment]
Thanks for your application

**Comment by jz2120100058** [comment]
Thanks for your application

**Comment by jz2120100058** [comment]
Thanks for your application

**Comment by jz2120100058** [comment]
Thanks for your application

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/153794869-2bc35b26-d9bf-4ac7-a87c-8d1c322a2f43.png)
Thanks for your application. There are two points need to be modified：
1.The TRC10 token shows a different address system with a short number.We do not support TRC10 tokens at this time，please check and remove them all；
2.New link invalid；

**Comment by 1337Tpunk** [comment]
Hello Jerry,

Here is the link and I have removed the entries with different address
systems.:

https://1337tpunk.com/1337tpunk.json

Let me know if there is anything else.

Kind Regards,

1337Tpunk
1337Tpunk.com



jerry ***@***.***> escreveu no dia segunda, 14/02/2022 à(s)
03:26:

**Comment by jz2120100058** [comment]
Hello 1337Tpunk,  the address of Token "XDV" is wrong.Please fix it.
![image](https://user-images.githubusercontent.com/20548311/154189373-7cfb910d-fe85-452b-847f-497753264ea9.png)

**Comment by jz2120100058** [comment]
![image](https://user-images.githubusercontent.com/20548311/154193345-42025948-9ac1-4417-95be-0976decbf29a.png)
"TNT" token  address cannot find in SunSwap, please remove it.

**Comment by 1337Tpunk** [comment]
Hello Jerry, thank you for your reply.

I removed XDV from the list and verified TNT and I believe the address/code
is correct as we can see from this link:

https://tronscan.io/#/token20/TL33cN6t22RcKyqPKkb14iVrPHDFaFMH7t

Please compare the link to the image you sent.

Thank you,

1337Tpunk
1337Tpunk.com

The list continues to be available here:

https://1337tpunk.com/1337tpunk.json

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I mean "TNT" addressd "TL33cN6t22RcKyqPKkb14iVrPHDFaFMH7t" cannot find in SunSwap Loop. The token in application list must already exsit in SunSwap Loop.

**Comment by 1337Tpunk** [comment]
Hi Jerry, no problem. I removed TNT from the list.

https://1337tpunk.com/1337tpunk.json

Kind Regards,

1337Tpunk
1337Tpunk.com


jerry ***@***.***> escreveu no dia quinta, 17/02/2022 à(s)
03:03:

**Comment by jz2120100058** [comment]
Hello 1337Tpunk,  Because the Token List addition review is very strict,  We'll take some time to review other information.

**Comment by 1337Tpunk** [comment]
Hello Jerry,

Thank you very much for the guidance.
I look forward to seeing it active and available.

Kind Regards,

1337Tpunk
1337Tpunk.com

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, thanks for your application and I'm sorry to have kept you waiting so long.
Except for tokens that already exist in “SunSwap Default List” and “Tron Alliance List”,there are thirty-three tokens are added to the application list. The thirty-three tokens are as follow：['KLV', 'DVK', 'KFI', 'UME', 'EFT', 'KODX', 'YFX', 'JM', 'Safe Money', 'CNS', 'CNR', 'BNKR', 'BNKRX', 'UP', 'CREED', 'CREEDX', 'TOFU', 'PNUT', 'RENEC', 'LDA', 'NOLE', 'SST', 'SOUL', 'ZLF', 'HORA', 'LUME', 'PLAT', 'MILK', 'PLAY', 'PRIMO', 'BBT', 'KTY', 'DOGE'].
Of the 33 tokens, “KLV” had the highest 14-day volume.This week “KVL” only ranked 284 in the whole SWAP V1 , and last week it only ranked 285. Therefore, these tokens do not qualify for the new list.But we will keep an eye on these tokens and contact you as soon as the situation changes.
The details are as follows：
![image](https://user-images.githubusercontent.com/20548311/155695802-4fa30c47-bf73-4d5b-a7a3-3baa8cf6f529.png)
![image](https://user-images.githubusercontent.com/20548311/155696644-cdcbf34d-1430-426a-86a2-c15019f9ddef.png)
![image](https://user-images.githubusercontent.com/20548311/155696014-cfa897e1-9c99-4380-9419-483a9379a6b4.png)
![image](https://user-images.githubusercontent.com/20548311/155696082-48430cad-ed8c-42d7-a317-4ad454c2b6d9.png)
Finally, I hope you are having a great day.

**Comment by 1337Tpunk** [comment]
Hello Jerry, I removed KLV.

Let me know if that is enough or if anything else is required.

Thank you!

Kind Regards,

1337Tpunk
1337Tpunk.com

jerry ***@***.***> escreveu no dia sexta, 25/02/2022 à(s)
10:07:

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.
Maybe I’m not describing it clear，I mean except for tokens that already exist in “SunSwap Default List” and “Tron Alliance List”,  KLV is the best performer token in the application list，but it doesn’t up to standard, so the rest tokens of the list are even less up to par.
Therefore, these tokens do not qualify for the new list.But we will keep an eye on these tokens and contact you as soon as the situation changes.
Finally, thank you again for your application.

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.
Maybe I’m not describing it clear,I mean except for tokens that already exist in “SunSwap Default List” and “Tron Alliance List”,  KLV is the best performer token in the application list，but it doesn’t up to standard, so the rest tokens of the list are even less up to par.
Therefore, these tokens do not qualify for the new list.But we will keep an eye on these tokens and contact you as soon as the situation changes.
Finally, thank you again for your application.

**Comment by jz2120100058** [comment]
Hello 1337Tpunk, I hope you are having a great day.
Maybe I’m not describing it clear, I mean except for tokens that already exist in “SunSwap Default List” and “Tron Alliance List”,  KLV is the best performer token in the application list，but it doesn’t up to standard, so the rest tokens of the list are even less up to par.
Therefore, these tokens do not qualify for the new list.But we will keep an eye on these tokens and contact you as soon as the situation changes.
Finally, thank you again for your application.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.

**Comment by 1337Tpunk** [comment]
Thank you for your time.

Maybe there could be a way to automate the process online making it easier
for anyone to create lists?

Who knows..

Have a good day.

Kind Regards,

1337Tpunk
