### ISSUE TITLE
Add JustList: {Revain List}

### ISSUE THREAD

**Issue by andrewrevain** [justswaporg/justlists#2523]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://revain.org/justlist.json
JustList Name: Revain List
Link to the official homepage of the JustList manager: https://revain.org

**More information:**
Revain is a review platform that aims to curate and reward user feedback on products and services by leveraging blockchain technology.

Revain is similar to other reviewing platforms such as Yelp and Trip Advisor, and encourages independent authors to write reviews and attach ratings to them. As posts are made, Revain aggregates, averages, and publicly displays corresponding scores and rankings to their platform.

As it stands, the project is built on both Ethereum and Tron and uses their technology to prevent relevant stakeholders from tampering with the reviews while rewarding users for their feedback.

See more https://www.kraken.com/ru-ru/learn/what-is-revain-rev

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.

**Comment by Yakuza9** [comment]
2523
