### ISSUE TITLE
Add JustList: {tronnew-list}

### ISSUE THREAD

**Issue by Digitaltoman** [justswaporg/justlists#2536]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL:  https://tron.data728.ir/tronnewlist.json
JustList Name: tronnew-list
Link to the official homepage of the JustList manager:

**Comment by jz2120100058** [comment]
Sorry, the issue will be closed as the URL and website cannot be accessed.Please resubmit.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
