### ISSUE TITLE
Hello,  i have a problem using api /v2/:token/tokens/:address with platform bitcoin and ethereum, msg='{status_code 503}'

### ISSUE THREAD

**Issue by Hjordaan2002** [justswaporg/justlists#2562]
Hello,  i have a problem using api /v2/:token/tokens/:address with platform bitcoin and ethereum, msg='{status_code 503}'
in addition, service parser have same error.
![image](https://user-images.githubusercontent.com/43730602/135130596-d1de2ef9-99c7-4371-adfb-73bb71ad5ba9.png)
Besides, api v3/tokens alaways return [] is it an error?
Looking forward to hearing from you

_Originally posted by @superphao in https://github.com/trustwallet/blockatlas/issues/1455#issuecomment-929402678_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
