### ISSUE TITLE
Add JustList: {MTC}

### ISSUE THREAD

**Issue by MTCPlatform** [justswaporg/justlists#2580]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

Name: MTC
Contract URL: https://tronscan.io/#/token20/TUbf4VHKqGRqQB6uhNdmssFwuA3TEX6cz7
Homepage: 
https://metatronchain.io/
https://metatronchain.net/
E-mail : support@metatronchain.info

[MTC WhitePaper_ver1.1_ENG.pdf](https://github.com/justswaporg/justlists/files/8174388/MTC.WhitePaper_ver1.1_ENG.pdf)

{
 "name": "MTC", #List name
 "logoURI": "https://metatronchain.io/assets/images/logo_mtc.png", #List logo uri
 "timestamp": 1610339529000, #Update time in millisecond
 "tokens": [{
 "chainId": 1, #ChainId, which is currently 1
 "address": "TUbf4VHKqGRqQB6uhNdmssFwuA3TEX6cz7", #Token address
 "name": "MTC", #Token name
 "symbol": "MTC", #Token symbol
 "decimals": 18, #Token decimals
 "logoURI": "https://metatronchain.io/assets/images/logo_mtc.png" #Token logo uri
 },
 {
 "chainId": 1,
 "address": "TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT",
 "name": "USDJ",
 "symbol": "USDJ",
 "decimals": 18,
 "logoURI": "https://coin.top/production/logo/usdj.png"
 }
 ],
 "version": { #Version info
 "major": 1, #Major version
 "minor": 0, #Minor version
 "patch": 0 #Patch version
 }
}

**Comment by jz2120100058** [comment]
Please submit your information in the correct format.Please resubmit.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
