### ISSUE TITLE
Add JustList: {MTC List}

### ISSUE THREAD

**Issue by MTCPlatform** [justswaporg/justlists#2628]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://metatronchain.io/mtcjson.php
JustList Name: MTC List
Link to the official homepage of the JustList manager: https://metatronchain.io/

More information: 

MTC Platform is a marketplace platform that handles data in all areas including society, economy, sports, culture, politics, science, and technology. Blockchain network of this platform is built in the form of P2P and mobile mining to provide a decentralized data chain in which all participants in the blockchain become producers and consumers at the same time, while  users experience enhanced security through the internal private chain. MTC(Metatronchain) is required to access the implemented decentralized data.

**Comment by jz2120100058** [comment]
Please resubmit your information in the correct URL.

**Comment by GitesParti343** [comment]
2628

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance, you can submit a new issue at it.
Thanks.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
