### ISSUE TITLE
添加JustList: {YUSD}

### ISSUE THREAD

**Issue by aoeng** [justswaporg/justlists#2631]
检查清单
- [ x ] **我已知晓此issue不是提交token而是提交JustList**
- [ x ] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [ x ] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: https://raw.githubusercontent.com/aoeng/younique/master/justlists.json
JustList 名称: YUSD-JustList
JustList 提交者的网站或主页:  https://www.youni.cool/tw/yusd

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
