### ISSUE TITLE
Add JustList: {Sunswap}

### ISSUE THREAD

**Issue by legendaryfinanceweb3game** [justswaporg/justlists#2646]
{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"LGF",
            "address":"TNhQvaZPerVLF6YUajsTEkHfzr7jBNXCR",
            "chainId":1,
            "decimals":18,
            "name":"Legendary Finance",
            "logoURI":"https://www.linkpicture.com/q/IMG1645697294176.png"
        },
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by jz2120100058** [comment]
Please resubmit your information in the correct format.
