### ISSUE TITLE
Add JustList: Brutus Token List

### ISSUE THREAD

**Issue by stevenstc** [justswaporg/justlists#2684]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://brutustoken.com/coin-list.json
JustList Name: Brutus Token List
Link to the official homepage of the JustList manager: https://brutustoken.com/

**Comment by jz2120100058** [comment]
Thanks for your application.
Please provide more information and stats of your project. such as, your website, whiter paper, user amount, audit report, social media, TVL and other important information(suggested but not limited), More information will help to speed up the review process.
Please share more info to us at: [support@sunswap.com](mailto:support@sunswap.com)
It would be great if you can also share your IM contact info, for example discord, Telegram and so on.
Thanks

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
