### ISSUE TITLE
Add JustList: {MYNN}

### ISSUE THREAD

**Issue by Janithkjw** [justswaporg/justlists#270]
{
   "name": "My1",
   "logoURI": "https://coin.top/production/upload/logo/TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS.png?t=1593603055162",
   "timestamp": 1610339529000,
   "tokens": [{
           "chainId": 1,
           "address": "TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS",
           "name": "Klever",
           "symbol": "KLV",
           "decimals": 10,
           "logoURI": "https://coin.top/production/upload/logo/TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS.png?t=1593603055162"
       },
   ],
   "version": {
       "major": 1,
       "minor": 0,
       "patch": 0
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
