### ISSUE TITLE
Add JustList

### ISSUE THREAD

**Issue by Nelsonsheph** [justswaporg/justlists#2701]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://Tron.net
JustList Name: Tron
Link to the official homepage of the JustList manager:
Tobieandrea75@gmail.com

**Comment by jz2120100058** [comment]
Sorry, the issue will be closed as the URL and website cannot be accessed.Please resubmit.
