### ISSUE TITLE
Add JustList: WRE Ecosystem

### ISSUE THREAD

**Issue by WreEcosystem** [justswaporg/justlists#2756]
JustList URL: https://tronscan.io/#/token20/TXrPGuk9ZcV6XyZ69DVfGwNfYJwrenrVcd
JustList Name: WRE Ecosystem
Link to the official homepage of the JustList manager: https://wre-ecosystem.com/

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct ListURL.Please resubmit.
