### ISSUE TITLE
Using `eth_sign` and then verifying the signature (recovering the address) the recovered address in sometimes wrong.

### ISSUE THREAD

**Issue by 846200** [justswaporg/justlists#2789]
Using `eth_sign` and then verifying the signature (recovering the address) the recovered address in sometimes wrong.

E.g. Signing the data
`0x68bfc34d28afcb7ae03691816548965dffba6c427c79d15fe6ef548384395fb0`
with the address
`0xe3aAd2d4f9545D3cE53Bb5cd9Ca929a9f7995837`
the result of TrustWallet is
`0xa20bdcf11c4c689edba3af62c531240c09d365233cc7e8934ad9c8ea7085b37a1f781f59e558e8dc8f46cf56964f373deaf70b61bd2b896b87a49c8b293cc3311b`

Now if we recover the address we get
`0x4d8d9d89b133024249651d9161F52a8c0D9d4e7e`

__Originally posted by @leroldary in https://github.com/trustwallet/trust-wallet-ios/issues/947__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by Avanotty27** [comment]
Ava wallet
