### ISSUE TITLE
添加JustList: {JustList name}

### ISSUE THREAD

**Issue by Paitson** [justswaporg/justlists#2797]
检查清单
- [x] **我已知晓此issue不是提交token而是提交JustList**
- [x] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [x] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: https://github.com/Paitson/dxds/blob/c25f2109cc81e4ccb24919324dd1d5d303a90083/dxds.justlists.ts
JustList 名称: DXDS LIST
JustList 提交者的网站或主页:https://www.sanqiu.cc/

**Comment by GitesParti343** [comment]
👍

**Comment by jz2120100058** [comment]
The Issue 2797 is the same as Issue 2796. Please do not submit twice.
