### ISSUE TITLE
Add JustList: {C23}

### ISSUE THREAD

**Issue by C23token** [justswaporg/justlists#2805]
Checklist
- [*] **I understand that this is not the place to request a token listing.**
- [*] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [*] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

JustList URL:  https://c23token.com/c23.ts
JustList Name:  C23
Link to the official homepage of the JustList manager: https://c23token.com

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
Hello,c23token.I hope you have a good day.
The c23 token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by jz2120100058** [comment]
Sorry, this issue will be closed . If you want to add a new list, please resubmit.
