### ISSUE TITLE
添加JustList: {AJ.VIP}

### ISSUE THREAD

**Issue by Andyok2022** [justswaporg/justlists#2832]
提交之前请删除下面的话:
**如果您没按照要求提交正确的JustList样式，您的issue将会被删除**

**您提交的JustList json格式必须满足下面链接中定义的例子格式**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

检查清单
- [x] **我已知晓此issue不是提交token而是提交JustList**
- [x] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [x] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: https://github.com/Andyok2022/justlists/blob/main/aj.vip.json
JustList 名称: AJ.VIP
JustList 提交者的网站或主页:https://aj.vip

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by Andyok2022** [comment]
I have created a new merge request, please handle it, thanks

**Comment by Sallukhanx** [comment]
Support me

SALMAN KHAN

**Comment by jz2120100058** [comment]
Hello,Andyok2022.I hope you have a good day.
The AJ.VIP token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by Andyok2022** [comment]
i have added

**Comment by jz2120100058** [comment]
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/20548311/171991422-b93f08e7-3c72-4f42-972d-8349750d1f47.png">
But I can not find.

**Comment by Andyok2022** [comment]
system has bugs  You search for the contract address

**Comment by Andyok2022** [comment]
search:TNTsQstXg6JyxZyNTJedJ1SbCirc1v9bz2

**Comment by jz2120100058** [comment]
Hello , Andyok2022 , I hope you have a good day.
I  mean  you have create token, but you must create exchange in SunSwap, then you can application add the Justlist.

**Comment by jz2120100058** [comment]
This issue will be closed, if you want to submit a new JustList, please resubmit.
