### ISSUE TITLE
Add JustList: {JustList CXTron}

### ISSUE THREAD

**Issue by c-exinsco** [justswaporg/justlists#2842]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/c-exinsco/CXTron/blob/main/lgflist.json
JustList Name: CXTron
Link to the official homepage of the JustList manager:

Slack: https://cexinscocrypt-dod6095.slack.com/
Facebook: https://facebook.com/cexinsco
LinkedIn: https://linkedin.com/in/cexinsco
Twitter: https://twitter.com/cexinsco
Instagram: https://www.instagram.com/cexinsco
Discord: https://discord.new/QQy9fskxavaD
Pinterest: https://pinterest.com/cexinsco
Reddit: https://www.reddit.com/user/cexinsco
Tiktok: https://tiktok.com/@cexinsco?lang=en
Telegram: https://t.me/cexinsco
Medium: https://c-exins-co.medium.com/
Youtube: https://www.youtube.com/channel/UCjtssoExd5cf9NNKooyvW4g
Website: https://www.c-exins.co/
Email: [info@c-exins.co](mailto:info@c-exins.co)

Saturday, 29 May, 2022
C-EXINS Blockchain Department, [Odeonus.com](http://odeonus.com/)

**Comment by jz2120100058** [comment]
Hello,c-exinsco.I hope you have a good day.
The CXT token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/20548311/172088524-c5ebd355-75a1-4a22-9ad9-228c4623a56e.png">

**Comment by jz2120100058** [comment]
This issue will be closed, if you want to submit a new JustList, please resubmit.
