### ISSUE TITLE
I want my transaction completed in my ethereum wallet 0x6EAaA0F842d214d54fed6495B9D9794Bf969238B

### ISSUE THREAD

**Issue by Nicholas4455** [justswaporg/justlists#2852]
I want my transaction completed in my ethereum wallet 0x6EAaA0F842d214d54fed6495B9D9794Bf969238B

__Originally posted by @Nicholas4455 in https://github.com/lightclient/go-ethereum/pull/7#discussion_r895633536__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
