### ISSUE TITLE
Add JustList: {Rielcoin}

### ISSUE THREAD

**Issue by vechet70** [justswaporg/justlists#286]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://rielcoin.org/rielcoin.json

Checklist
- [ yes] **I understand that this is not the place to request a token listing.**
- [ yes] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ yes] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://rielcoin.org/rielcoin.json
JustList Name: Rielcoin
Link to the official homepage of the JustList manager:https://rielcoin.org/

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
