### ISSUE TITLE
这个是我实际想操作的

### ISSUE THREAD

**Issue by Abas0778** [justswaporg/justlists#2860]
这个是我实际想操作的

https://user-images.githubusercontent.com/101307399/169261885-ba4fb630-dcf5-43d9-b5c0-020ec1eac315.mp4

上图红圈里面的`【【`还是已经删除的那个双链的

_Originally posted by @Temacc0531 in https://github.com/siyuan-note/siyuan/issues/4950#issuecomment-1131463898_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
