### ISSUE TITLE
Add JustList: {PCOIN}

### ISSUE THREAD

**Issue by pcocrypto** [justswaporg/justlists#2865]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/pcocrypto/justlists/blob/main/example.justlists.ts
JustList Name: PCOIN
Link to the official homepage of the JustList manager:

**Comment by pcocrypto** [comment]
Telegram : https://t.me/pumachain
Twitter : https://twitter.com/pumachains

**Comment by jz2120100058** [comment]
Hello, pumacoincrypto,I hope you have a good day.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

**Comment by pcocrypto** [comment]
Hi
JustList URL: https://github.com/pcocrypto/justlists/blob/main/example.justlists.ts
Thanks

**Comment by jz2120100058** [comment]
Hello, pcocrypto,thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by pcocrypto** [comment]
Before submission deletes this line:
THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT

YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist

I understand that this is not the place to request a token listing.
I have tested that my JustList is compatible by pasting the URL into the add a list UI at justswap.org.
I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

Please provide the following information for your token.
JustList URL must be HTTPS.

JustList URL: https://github.com/pcocrypto/justlists/blob/main/example.justlists.ts
JustList Name: PCOIN
Link to the official homepage of the JustList manager:
Site :  https://pcocrypto.com
Telegram : https://t.me/pumachain
Twitter : https://twitter.com/pumachains

**Comment by jz2120100058** [comment]
Hello, pcocrypto,thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed, if you want to add justlist please resubmit.
