### ISSUE TITLE
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.

### ISSUE THREAD

**Issue by TanCheeHwa** [justswaporg/justlists#2868]
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.

__最初由 @github-actions 在 https://github.com/ethereum/EIPs/issues/2338#issuecomment-986086244 发布__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
