### ISSUE TITLE
Add JustList: {JustList XBA}

### ISSUE THREAD

**Issue by hieuthch** [justswaporg/justlists#2875]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/Legdndaryfinance/Legendary-Finance-official-source-code/compare/main...hieuthch:patch-1
JustList Name: XBA
Link to the official homepage of the JustList manager:https://xbank247.com/

**Comment by hieuthch** [comment]
Audits:https://www.certik.com/projects/xbank?utm_source=CMC&utm_campaign=AuditByCertiKLink
Twitter:https://twitter.com/XBANK247
Telegram:https://t.me/xbaglobal
whiter paper:https://whitepaper.xbank247.com/
Website:https://xbank247.com/

**Comment by jz2120100058** [comment]
Hello, hieuthch.I hope you have a good day.
The AJ.VIP token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
This issue will be closed, if you want to submit a new JustList, please resubmit.
