### ISSUE TITLE
Add JustList: {Pcoin}

### ISSUE THREAD

**Issue by pumacoincrypto** [justswaporg/justlists#2882]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL:  https://github.com/pumacoincrypto/TRC20/blob/main/pcoin.justlists.ts
JustList Name:  Pcoin
Link to the official homepage of the JustList manager:
Twitter : https://twitter.com/pumachains
Telegram : https://t.me/pumachain

**Comment by jz2120100058** [comment]
Hello,pumacoincrypto.I hope you have a good day.
The Pcoin token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by pumacoincrypto** [comment]
Please help me create createExchange in SunSwap

**Comment by pumacoincrypto** [comment]
Minimum Energy For Call Smart Contract....

**Comment by jz2120100058** [comment]
Hello,pumacoincrypto. You must  create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by pumacoincrypto** [comment]
Hello , jz2120100058
i create createExchange in SunSwap but OUT_OF_ENERGY
https://tronscan.org/#/transaction/326a7503c0527aa7735964780ff1caf0d7017f6daf6d36f881890b94df433966
minimum fee limit?

**Comment by jz2120100058** [comment]
https://developers.tron.network/docs/faq#7-how-to-solve-out_of_energy-error            You can refer to it.

**Comment by pumacoincrypto** [comment]
how calc limit fee and calc energy for smartcontract with sdk or api

**Comment by jz2120100058** [comment]
https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract          You can refer to it

**Comment by pumacoincrypto** [comment]
https://tronscan.org/#/transaction/81db650c42c3cc93d3e037820cc5702b1b0b5d2640f8af9bad2c0f903321f1d8
this transaction has error
If I had the necessary energy

**Comment by pumacoincrypto** [comment]
call method createExchange
https://tronscan.org/#/transaction/5be9b2f0e742c53dd0952f45b811f96b2226209a97c8337ecfcaf96c4e0d63e6
it's ok

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by pumacoincrypto** [comment]
When will it be listed?

**Comment by jz2120100058** [comment]
Sorry, We're not sure of the time. We are currently very tight on development resources and adding new lists on a case-by-case basis. Maybe you can join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by pumacoincrypto** [comment]
In your opinion, we include this request and what are its conditions

**Comment by jz2120100058** [comment]
Maybe you can refer to the conditions of tronalliance:

**Comment by jz2120100058** [comment]
Maybe you can refer to the conditions of tronalliance:
        1.The token page on Transcan has a official website
        2.The token page on Transcan needs at least 1 social profile
        3.Transaction volume over $10,000 in 24 hours

**Comment by pumacoincrypto** [comment]
Did you find the Pcoin collection valuable for listing?

**Comment by jz2120100058** [comment]
You must make your own decisions.

**Comment by pumacoincrypto** [comment]
Pcoin
https://sunswap.com/#/scan/detail/TYnBXH9TsuzY8rviUN5EKytKf7D99z3gci

**Comment by pumacoincrypto** [comment]
Hi
Pcoin Not yet reviewed???

**Comment by jz2120100058** [comment]
Hello, pumacoincrypto,I hope you have a good day.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

You can refer to the conditions of tronalliance:
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.Transaction volume over $10,000 in 24 hours
If the above conditions are met, it will automatically join the tronalliance list.

**Comment by jz2120100058** [comment]
This issue will be closed, if you want to submit a new JustList, please resubmit.
