### ISSUE TITLE
accident 

### ISSUE THREAD

**Issue by ghost** [justswaporg/justlists#2911]
- [ ]

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by mundobear1** [comment]
I didn’t even mean to post anything on GitHub.. I’m clearly inexperienced and thst was a total accident 

Sent from my iPhone

On Jul 7, 2022, at 9:53 PM, jerry ***@***.***> wrote:

﻿
Please submit the correct information, invalid information will cause the issue to close
