### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by youtube2688** [justswaporg/justlists#2943]
{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"MYDOG",
            "address":"TMn2zeWbu9p71t76aiug4iHX8h9FL5AVkD",
            "chainId":1,
            "decimals":2,
            "name":"MYDOG Coin",
            "logoURI":"https://raw.githubusercontent.com/youtube2688/mydog/main/78.png"
        },

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.Please resubmit.
