### ISSUE TITLE
Add JustList: {CWNMediaList}

### ISSUE THREAD

**Issue by cwnmedia** [justswaporg/justlists#2946]
JustList URL:  https://cwn.media/CWNMediaList.ts
JustList Name: CWNMediaList
Link to the official homepage of the JustList manager: https://cwn.media

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
The CWNMEDIA token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.

**Comment by cwnmedia** [comment]
I forked the tronalliance with my account https://github.com/cwnmedia/tronalliance and added the token KITTEE to it. I do not know how to reach the person at tronalliance for them to test the code and to see if they would add it to their tronalliance. Any help would be appreciated.

Thank you

CWN Media


On July 20, 2022 at 2:36:35 AM, jerry ***@***.***) wrote:

Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
You can refer to the conditions of tronalliance:
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.Transaction volume over $10,000 in 24 hours
If the above conditions are met, it will automatically join the tronalliance list.

**Comment by cwnmedia** [comment]
Jerry,

Thank you very much for your email.

Website: https://kittee.shop will be complete early to mid next week.

Social Media (currently)
Twitter: https://twitter.com/KITTEETOKEN
Telegram: https://t.me/kitteetoken

The $10k Volume will be there soon.

Thank you

KITTEE


On July 21, 2022 at 2:45:55 AM, jerry ***@***.***) wrote:

You can refer to the conditions of tronalliance:
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.Transaction volume over $10,000 in 24 hours
If the above conditions are met, it will automatically join the tronalliance list.

**Comment by cwnmedia** [comment]
Hello team,

The website is up for KITTEE (https://kittee.shop), below is the link to the Token information. 

https://kittee.shop/kittee-kte-token-trx-trc-20-tron-network/


Thank you

CWN Media


On July 29, 2022 at 5:36:50 PM, CWN Media ***@***.***) wrote:

Hello,

1. https://kitt.shop is the. Official website (The site out of maintenance mode by by Monday August 1st)
2. https://twitter.com/kitteetoken
2a. https://t.me/kitteetoken
3. Currently over $10,000 in transactions in past 24 hours.


Thank you

CWN Media


On July 21, 2022 at 2:45:55 AM, jerry ***@***.***) wrote:

You can refer to the conditions of tronalliance:
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.Transaction volume over $10,000 in 24 hours
If the above conditions are met, it will automatically join the tronalliance list.

**Comment by jz2120100058** [comment]
Hello cwnmedia, I hope you have a good day.
 I rechecked the conditions of tronalliance:
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If  the  tokens  move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed.
If you meet any question , you can leave a comment at https://github.com/listtronalliance/tronalliance. The team of tronalliance will answer for you.

**Comment by cwnmedia** [comment]
Please review https://github.com/listtronalliance/tronalliance/issues/3#issuecomment-1206356520

Thank you

**Comment by jz2120100058** [comment]
OK, the team of tronalliance will answer for you.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed, if you want to add justlist please resubmit.
