### ISSUE TITLE
https://link.trustwallet.com/send?coin=195&address=TYqUrXbGHg8hsdoiUXnvHzXFYYBrc6Fnmd

### ISSUE THREAD

**Issue by trastvolt** [justswaporg/justlists#2962]
My Public Address to Receive TRX TYqUrXbGHg8hsdoiUXnvHzXFYYBrc6Fnmd

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=195&address=TYqUrXbGHg8hsdoiUXnvHzXFYYBrc6Fnmd

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
