### ISSUE TITLE
添加JustList: {JustList name}

### ISSUE THREAD

**Issue by ygz10525** [justswaporg/justlists#3031]
JustList URL: https://github.com/EOTCotc/ListTokens/blob/main/trxTokenLists/eotcswap.json
JustList 名称: EotcSwap List
JustList 提交者的网站或主页:https://eotc.im/

**Comment by jz2120100058** [comment]
Hello,xiaoMocygz,I hope you have a good day.
First,The “EOTC” token can not find in SunSwap V1 ,V1.5 and V2, you must first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.
Second,We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

**Comment by jz2120100058** [comment]
Sorry, your issue will be closed, if you want to add justlist please resubmit.
