### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by DrZain11** [justswaporg/justlists#3048]
Before submission deletes this line:

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
{
    "name": "TVD List",
    "logoURI": "http://tokenvest.io/v12_files/logo-light.png",
    "timestamp": 1660291736000,
    "version": {
        "major": 1,
        "minor": 4,
        "patch": 47
    },
    "tokens": [
        {
            "symbol":"TVD",
            "address":"TWiwCRJPAKPpfMiEWpDrpYQKwHWY5wwPjC",
            "chainId":1,
            "decimals":18,
            "name":"TOKEN VEST Dinar",
            "logoURI":"https://static.tronscan.org/production/upload/logo/TWiwCRJPAKPpfMiEWpDrpYQKwHWY5wwPjC.png?t=1656366332208"
        }
    ]
}

**Comment by jz2120100058** [comment]
https://github.com/justswaporg/justlists/issues/3051
