### ISSUE TITLE
Add JustList: {Real Estate Coin}

### ISSUE THREAD

**Issue by ChrisExpert** [justswaporg/justlists#3121]
![WhatsApp_Image_2022-07-18_at_11 39 19_PM-removebg-preview](https://user-images.githubusercontent.com/114649849/192974694-4cd2fd95-9eb3-47c0-b457-ba48a22fc09d.png)
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://www.therealcoin.org/
JustList Name: Real Estate Coin
Link to the official homepage of the JustList manager:
https://tronscan.org/#/token20/TAGA7iM21RXsWwdZA65HejaAsSpDc67aTQ

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close. If you want to submit a new JustList, please resubmit.
