### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by ChrisExpert** [justswaporg/justlists#3126]
REAL ESTATE COIN (REOC)
CHANGING THE WAY PEOPLE INVEST IN REAL ESTATE!

Welcome to the Future of Real Estate Investing.

SIMPLE, AFFORDABLE, AND MORE EFFECTIVE THAN EVER:
Real Estate is a great investment option. It generates ongoing passive income and is a long-term investment because the value increases over time. It is a very common strategy for building wealth.

WHY YOU SHOULD CONSIDER INVESTING IN REAL ESTATE CRYPTO COIN:
Investing in Real Estate provides you with a tangible asset that will generate a reliable source of income each month in addition to appreciation. Real Estate is also independent of the stock market, so it is a great way to diversify your portfolio and mitigate your overall risk.

REVOLUTIONIZING REAL ESTATE CROWDFUNDINGWITH CRYPTOCURRENCY (REOC)CREATING A ROBUST AND SCALABLE REAL ESTATE OWNEDCRYPTOMARKET:
Now you can invest at low-cost with great returns, diversified portfolio of institutional-quality Real Estate with the Real Estate Crypto Coin. Modern technology and internal experience are used to minimize costs and increase your long-term profit. 

IT IS SIMPLE TO START:
Creating an account with Real Estate Coin is quick and easy. Funding your account doesn't involve filling out a ton of paperwork.

ISSUE-FREE
NON-CRYPTO INVESTMENT/DIRECT PAYMENT
In order to participate in the Real Estate Coin Wealth Benefits, The Real Estate Coin grants those who are unfamiliar with cryptocurrencies the option of investing directly through PayPal. We do everything within our power to ensure that investing in the Real Estate Coin is straightforward, stress-free, and available to a global audience.

YOUR PORTFOLIO IS SUPPORTED BY RELIABLE, HIGH-QUALITY ASSETS
OUR ASSETS = YOUR ASSETS
Your returns are based on our assets. We use the collective purchasing power of our investor community with our wide network and industry knowledge to acquire high-quality assets, including debt, equity, commercial, residential, and other types of assets.
By purchasing assets for less than their market value—typically less than their replacement cost—we employ a "value investing" technique. Our staff then strives to gradually raise each asset's value through active management and collaboration with neighborhood businesses.
The REAL ESTATE COIN portfolio was especially created with the goal of being able to withstand protracted times of economic hardship. Nothing can be guaranteed, but we believe the REAL ESTATE COIN portfolio is, from a risk-adjusted-return perspective, due to our cautious approach and thorough underwriting procedures.

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://www.therealcoin.org/
JustList Name: THE REAL ESTATE COIN
Link to the official homepage of the JustList manager:

![WhatsApp_Image_2022-07-18_at_11 39 19_PM-removebg-preview](https://user-images.githubusercontent.com/114649849/193368043-1aaa1a18-5c4f-4b6e-aae4-8e8494e0fb59.png)

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
