### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by isge90** [justswaporg/justlists#3139]
{"address":"dnt3agxsl5emenxrg7cbc7hgc5df6abtpui7yvfdagpbgkkecj4rcqad.onion","status"data":[70016,"/Satoshi:22.0.0(RoninDojo 1.14.1)/",1665382865,1037,758012,bitcoin address:1HqJKQ2KeDishV5SJmFxmCJ2q4foQNcjjA{"address":"dnt3agxsl5emenxrg7cbc7hgc5df6abtpui7yvfdagpbgkkecj4rcqad.onion","status":","data":[70016,"/Satoshi:22.0.0(RoninDojo 1.14.1)/",1665382865,1037,758012,Bitcoin address :1HqJKQ2KeDishV5SJmFxmCJ2q4foQNcjjA 0.0,0.0,null,"TOR","Tor network"],"mbps":0.0,0.0, Bitcoin address :1HqJKQ2KeDishV5SJmFxmCJ2q4foQNcjjA,"TOR","Tor network"],"mbps"bitcoin:1HqJKQ2KeDishV5SJmFxmCJ2q4foQNcjjA

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
