### ISSUE TITLE
TPmStdKfvscbXhowveCHjarSkQN5qpvWD9.justlists.ts

### ISSUE THREAD

**Issue by FishKoi** [justswaporg/justlists#33]
{
   "name": "FIRST INTERCHANGEABLE TOKEN", #List name
   "logoURI": "https://coin.top/production/upload/logo/TPmStdKfvscbXhowveCHjarSkQN5qpvWD9.png", #List logo uri
   "timestamp": 1610339529000, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TPmStdKfvscbXhowveCHjarSkQN5qpvWD9", #Token address
           "name": "FIRST INTERCHANGEABLE TOKEN", #Token name
           "symbol": "FIT", #Token symbol
           "decimals": 6, #Token decimals
           "logoURI": "https://coin.top/production/upload/logo/TPmStdKfvscbXhowveCHjarSkQN5qpvWD9.png" #Token logo uri
       }
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
