### ISSUE TITLE
Add JustList: {NUBA)

### ISSUE THREAD

**Issue by criptocomunidad** [justswaporg/justlists#3388]
JustList URL: https://raw.githubusercontent.com/criptocomunidad/justlists/NUBA-Justlist/NUBA.json)
JustList Name: NUBA
Link to the official homepage of the JustList manager: www.nubaht.com

**Comment by jz2120100058** [comment]
Thanks for reaching out.
We are currently very tight on development resources and adding new lists on a case-by-case basis.
If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks.

**Comment by jz2120100058** [comment]
please refer to https://github.com/justswaporg/justlists/issues/3625
