### ISSUE TITLE
0x0008d2abf5Ab348137CdcA8b4AA9674c0e4367E4

### ISSUE THREAD

**Issue by dosseyson** [justswaporg/justlists#3444]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by dosseyson** [comment]
world Kooperation Investment social humanitäre Projekt ab 300000 euro

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by dosseyson** [comment]
Super

**Comment by GitesParti343** [comment]
Hi im a ok d'or coperate but Nevers claim...how the procédure for receice
my part ... Explain me please

Le lun. 20 févr. 2023, 08 h 22, dosseyson ***@***.***> a
écrit :
