### ISSUE TITLE
Add JustList: REDAN

### ISSUE THREAD

**Issue by satzcryptos** [justswaporg/justlists#348]
JustList URL:  https://www.redannet.com/token/swap/list.json
JustList Name: Redan Coin
JustList: https://www.redannet.com

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.

**Comment by satzcryptos** [comment]
Hi @jeffwami, Could you please the suggest / share the correct format example. let me follow the same. Thanks.
