### ISSUE TITLE
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

### ISSUE THREAD

**Issue by alaslyalasel** [justswaporg/justlists#3524]
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 21407 ms: Couldn't connect to server

_Originally posted by @Mohammadqasimkhuroo in https://github.com/nvm-sh/nvm/issues/2935#issuecomment-1426941924_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
