### ISSUE TITLE
BT Coin Mining drhamedhiasat0@gmail.com

### ISSUE THREAD

**Issue by doctorhamed** [justswaporg/justlists#3569]
Hey I have Installed this App BT Coin Mining and Mine BTC on Play Store 
https://play.google.com/store/apps/details?id=com.bnx.dacoi&referrer=r8Md2qDFCiSGTibI1mWg2LvpnFm1

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
