### ISSUE TITLE
0xFe48C5588D6116D5827F3AA4911D23B6F784F3C8

### ISSUE THREAD

**Issue by Tranhung2h** [justswaporg/justlists#3617]
0xFe48C5588D6116D5827F3AA4911D23B6F784F3C8

_Originally posted by @Godaiandi in https://github.com/justswaporg/justlists/issues/2748#issuecomment-1340994176_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
