### ISSUE TITLE
Add JustList: {JustList name}wc:29b9bfecbe44574dc744a798ad3e31b844e21527f73e591135c18ee515e668ac@2?relay-protocol=irn&symKey=176d436a212364f5e37aa9b44da7e58a8e74c212094f526adb696bc4038a0f4c

### ISSUE THREAD

**Issue by truongnghia** [justswaporg/justlists#3632]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by truongnghia** [comment]
Re: [justswaporg/justlists] Add JustList: {JustList name}wc:29b9bfecbe44574dc744a798ad3e31b844e21527f73e591135c18ee515e668ac@2?relay-protocol=irn&symKey=176d436a212364f5e37aa9b44da7e58a8e74c212094f526adb696bc4038a0f4c (Issue #3632)
