### ISSUE TITLE
BOB.justlists

### ISSUE THREAD

**Issue by ooloox3x** [justswaporg/justlists#3691]
{
    "BOB Coins":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"BOB",
            "address":"TMVu7ikeLXCCw336HeA4dAi4zqm6TG6pwu",
            "chainId":1,
            "decimals":6,
            "name":"BOB Coins",
            "logoURI":"https://www.huobi.com/learn/wp-content/uploads/2021/09/tether-6334564_1280.png"
        },
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by jz2120100058** [comment]
Hello,[ooloox3x](https://github.com/ooloox3x), I hope you have a good day. Thanks for reaching out. Please note the following two points：
First, please create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.ans.
Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks

**Note:
_If the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed_**

**Comment by Marodero56** [comment]
Go

**Comment by Marodero56** [comment]
https://github.com/justswaporg/justlists/issues/3691#issue-1717866750

**Comment by jz2120100058** [comment]
Sorry, this issue will be colsed. If you want to apply for a new list, please resubmit.
