### ISSUE TITLE
address: 0xDCb5712A15f42A76C379FcDc982978a09D66C4F7, domain:

### ISSUE THREAD

**Issue by Amazinggrace07** [justswaporg/justlists#3695]
address: 0xDCb5712A15f42A76C379FcDc982978a09D66C4F7, domain: 

_Originally posted by @Panchobeltran702 in https://github.com/justswaporg/justlists/issues/3694_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by Panchobeltran702** [comment]
I dont understand
