### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by howtosuck** [justswaporg/justlists#372]
{
    "name":"PEARL",
    "tokens":[
        {
            "symbol":"PEARL",
            "address":"TGbu32VEGpS4kDmjrmn5ZZJgUyHQiaweoq",
            "chainId":1,
            "decimals":18,
            "name":"Pearl Finance",
            "logoURI":"https://assets.coingecko.com/coins/images/12305/small/pearl_finance_logo.png?1599017130"
        }
   ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by howtosuck** [comment]
fcking github i just wonna to trade pearl

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
