### ISSUE TITLE
Automatically generated. Please make sure to update the CHANGELOG.

### ISSUE THREAD

**Issue by mail731212** [justswaporg/justlists#3727]
Automatically generated. Please make sure to update the CHANGELOG.

__Originally posted by @pagerduty-api-schema-bot in https://github.com/PagerDuty/api-schema/pull/380__

__Originally posted by @mail731212 in https://github.com/Stability-AI/StableStudio/issues/80__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
