### ISSUE TITLE
> > @mail731212

### ISSUE THREAD

**Issue by mail731212** [justswaporg/justlists#3728]
> > @mail731212 
> > 
> > 
> > __Originally posted by @mail731212 in https://github.com/tronprotocol/java-tron/issues/5259#issuecomment-1575678386__
> 
> 

__Originally posted by @mail731212 in https://github.com/Uniswap/token-lists/issues/376#issuecomment-1575678973__

**Comment by mail731212** [comment]
> > > @mail731212 
> > > 
> > > 
> > > __Originally posted by @mail731212 in https://github.com/tronprotocol/java-tron/issues/5259#issuecomment-1575678386__
> > 
> > 
> 
> 
> 
> __Originally posted by @mail731212 in https://github.com/Uniswap/token-lists/issues/376#issuecomment-1575678973__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by mail731212** [comment]
> Please submit the correct information, invalid information will cause the issue to close

**Comment by mail731212** [comment]
Mail731212

**Comment by mail731212** [comment]
> Please submit the correct information, invalid information will cause the issue to close

**Comment by mail731212** [comment]
@jz2120100058
