### ISSUE TITLE
Please submit the correct information, invalid information will cause the issue to close

### ISSUE THREAD

**Issue by mail731212** [justswaporg/justlists#3736]
Please submit the correct information, invalid information will cause the issue to close

__Originally posted by @jz2120100058 in https://github.com/justswaporg/justlists/issues/3728#issuecomment-1576013887__

__Originally posted by @mail731212 in https://github.com/Stability-AI/StableStudio/issues/81__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
