### ISSUE TITLE
> I think we should follow this guy's advice: https://github.com/isaacs/github/issues/750#issuecomment-242220908

### ISSUE THREAD

**Issue by mail731212** [justswaporg/justlists#3737]
> I think we should follow this guy's advice: https://github.com/isaacs/github/issues/750#issuecomment-242220908

Actually, my advice there is somewhat outdated.  The current best practice is to search https://github.com/github/feedback/discussions: if you find a discussion for this, chime in there, & refer here (if not already linked); else, open 1 up to do that.

__Originally posted by @TPS in https://github.com/isaacs/github/issues/750#issuecomment-872563253__

__Originally posted by @mail731212 in https://github.com/mail731212/kun731020/issues/8__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
