### ISSUE TITLE
Addname": "TokenListExample", #List name    "logoURI": "https://coin.top/production/logo/usdj.png", #List logo uri    "timestamp": 1610339529000, #Update time in millisecond    "tokens": [{            "chainId": 1, #ChainId, which is currently 1            "address": "TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9", #Token address            "name": "BitCoin", #Token name            "symbol": "BTC", #Token symbol            "decimals": 8, #Token decimals            "logoURI": "https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png" #Token logo uri        },        {            "chainId": 1,            "address": "TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT",            "name": "USDJ",            "symbol": "USDJ",            "decimals": 18,            "logoURI": "https://coin.top/production/logo/usdj.png"        }    ],    "version": { #Version info        "major": 1, #Major version        "minor": 0, #Minor version        "patch": 0  #Patch version    } } JustList: {JustList name}

### ISSUE THREAD

**Issue by davoodSadeghi** [justswaporg/justlists#375]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [ ] **I understand that this is not the place to request a token listing.**
- [ ] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
