### ISSUE TITLE
Ass

### ISSUE THREAD

**Issue by mahmod87** [justswaporg/justlists#3767]
مُرسل من بريد Yahoo لجهاز iPhone

بتاريخ الجمعة, حزيران 23, 2023, 5:05 م، jerry ***@***.***> كتب:

Closed #3758 as completed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

_Originally posted by @mahmod87 in https://github.com/justswaporg/justlists/issues/3758#issuecomment-1604373131_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
