### ISSUE TITLE
This example is missing an import for `ZkSyncWallet`

### ISSUE THREAD

**Issue by IMOLE10** [justswaporg/justlists#3814]
This example is missing an import for `ZkSyncWallet`

_Originally posted by @kailash-manasarovar in https://github.com/matter-labs/zksync-web-era-docs/pull/505#discussion_r1224330323_

_Originally posted by @Blonde488 in https://github.com/tronscan/tron-tvl-list/issues/25_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
