### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by Vadrezz186** [justswaporg/justlists#3859]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

{
        "symbol":"TCPct",
        "address":"TQG8XGXYzRTciGiR8yjPv7yme2AVJ2n12b",
        "chainId":1,
        "decimals":8,
        "name":"TCPcent",
        "logoURI":"https://tcp-market.com/icons/Logo_TCP.png"
    }

**Comment by jz2120100058** [comment]
Hello,[Vadrezz186](https://github.com/Vadrezz186), I hope you have a good day. Thanks for reaching out. Please note the following two points：
First, please create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.ans.
Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks

_**Note:
If the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed**_

**Comment by jz2120100058** [comment]
Sorry, this issue will be colsed. If you want to apply for a new list, please resubmit.
