### ISSUE TITLE
Reopened. Link to the old PR: https://github.com/matter-labs/zksync-web-era-docs/pull/505

### ISSUE THREAD

**Issue by IMOLE10** [justswaporg/justlists#3884]
Reopened. Link to the old PR: https://github.com/matter-labs/zksync-web-era-docs/pull/505

_Originally posted by @petarTxFusion in https://github.com/matter-labs/zksync-web-era-docs/pull/654_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by Ozgurka** [comment]
Benim pi coinler ne olacak?
Ve Cat star

25 Ağu 2023 Cum 05:23 tarihinde jerry ***@***.***> şunu yazdı:
