### ISSUE TITLE
https://github.com/justswaporg/justlists/issues/3619

### ISSUE THREAD

**Issue by Sadeghi1017** [justswaporg/justlists#3920]
https://github.com/justswaporg/justlists/issues/3619

_Originally posted by @jz2120100058 in https://github.com/justswaporg/justlists/issues/3625#issuecomment-1545052259_

**Comment by Nelsonsheph** [comment]
My ask , what am I to do with it , Im new an confused and lost.

**Comment by jz2120100058** [comment]
Thanks for reaching out. As said before，please note the following two points：
First, please create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf
Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks

Note:
If the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed

**Comment by TJTua8EFotucUHhXsfFh7se22ExNEd28D4** [comment]
0
