### ISSUE TITLE
> https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:8323803a-e3cf-45eb-baf7-77af4f81734f

### ISSUE THREAD

**Issue by ashleyjaco** [justswaporg/justlists#3928]
> https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:8323803a-e3cf-45eb-baf7-77af4f81734f

__

_Originally posted by @ashleyjaco in https://github.com/ashleyjaco/ashleyj/issues/1#issuecomment-1731349917_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
