### ISSUE TITLE
Share Uniswap - 1% - 📘/ENS - 0.0074484<>0.0075989 Info

### ISSUE THREAD

**Issue by Whatafac** [justswaporg/justlists#3978]
https://rainbow.me/0xb8c2C29ee19D8307cb7255e1Cd9CbDE883A267d5?family=uniswap-v3-positions&nft=0x8d459bA159dB4C871a789e95A4114485E9aD10dA

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
