### ISSUE TITLE
LIsten JPM

### ISSUE THREAD

**Issue by USDJPM** [justswaporg/justlists#3982]
"symbol":"JPM",

"address":"TRtgjeEnCYK5LHgZui47ph3ge6dSyiPswJ",

"chainId":1,

"decimals":18,

"name":"JPM",

"logoURI":"https://github.com/USDJPM/JPM/blob/main/logo.png"

**Comment by jz2120100058** [comment]
Hello,USDJPM ,thanks for reaching out. Please note the following two points：
First, please create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf
Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks

Note:
If the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed

**Comment by USDJPM** [comment]
Hi thanks for the reply, I've already sent it to throne aliyans

пт, 27 окт. 2023 г. в 06:24, jerry ***@***.***>:

**Comment by USDJPM** [comment]
https://github.com/USDJPM/tronalliance

пт, 27 окт. 2023 г. в 06:31, Mr Takoshi ***@***.***>:

**Comment by USDJPM** [comment]
https://github.com/USDJPM/tronalliance/blob/main/tronalliance.json

пт, 27 окт. 2023 г. в 06:34, Mr Takoshi ***@***.***>:

**Comment by jz2120100058** [comment]
Hello,USDJPM. Please first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf

Then if the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed

**Comment by USDJPM** [comment]
https://www.sunswap.com/docs/sunswap-interfaces_en.pdf.ans Hi, this link
says it doesn't work error code 404

ср, 1 нояб. 2023 г. в 07:29, jerry ***@***.***>:

**Comment by jz2120100058** [comment]
Sorry, this is new link:https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf.

**Comment by srbaeza-ai** [comment]
https://github.com/justswaporg/justlists/commit/c6e648d3435e68be01e137973bef9005b29f1be5
