### ISSUE TITLE
A story from AirDAO on Medium

### ISSUE THREAD

**Issue by JRAAH** [justswaporg/justlists#3994]
Read this story from AirDAO on Medium: https://blog.airdao.io/airdao-tokenomics-update-amb-hard-cap-node-rewards-75a34853176e![shared_image.jpg](https://github.com/justswaporg/justlists/assets/111725761/5b45cc4d-5359-4826-adfa-c415ee7fe8a9)

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
