### ISSUE TITLE
يثAdd JustList: {JustList name}

### ISSUE THREAD

**Issue by AHMAD12006** [justswaporg/justlists#4026]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: 
JustList Name: 
Link to the official homepage of the JustList manager:

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by AHMAD12006** [comment]
16085200249287232},"4930405c-4f62-5664-bb65-f8b300cbf220":{"usd":0.00639791,"usd_24h_change":1.6532460072411868,"eur":0.0059869,"eur_24h_change":1.5647879847529256,"gbp":0.00521999,"gbp_24h_change":1.7432809983314184,"rub":0.590585,"rub_24h_change":1.9287458882644153,"inr":0.532938,"inr_24h_change":1.6643462619300065,"cny":0.04661199,"cny_24h_change":1.7090879332217854,"try":0.182351,"try_24h_change":1.6108180011012256,"cad":0.00882371,"cad_24h_change":1.787200326075165,"dkk":0.04465404,"dkk_24h_change":1.574076257149926},"7ffc9561-464f-5e22-ad6a-9bcc9ac8537e":{"usd":0.701174,"usd_24h_change":null,"eur":0.617176,"eur_24h_change":null,"gbp":0.516005,"gbp_24h_change":null,"rub":52.9,"rub_24h_change":null,"inr":52.05,"inr_24h_change":null,"cny":4.47,"cny_24h_change":null,"try":9.73,"try_24h_change":null,"cad":0.886487,"cad_24h_change":null,"dkk":4.59,"dkk_24h_change":null},"9978ace7-7a98-5960-887d-b35d65a33c5f":{"usd":0.354492,"usd_24h_change":1.1390522347426153,"eur":0.331719,"eur_24h_change":1.0510416604772956,"gbp":0.289226,"gbp_24h_change":1.228631800811507,"rub":32.72,"rub_24h_change":1.4131585515786231,"inr":29.53,"inr_24h_change":1.1500963408867078,"cny":2.58,"cny_24h_change":1.1946116948727863,"try":10.1,"try_24h_change":1.0968388426696731,"cad":0.488899,"cad_24h_change":1.2723289709194672,"dkk":2.47,"dkk_24h_change":1.0602829499000315},"5611d328-30e9-5319-8c59-7abc6c462b2b":{"usd":16.69,"usd_24h_change":1.4942620306114063,"eur":15.62,"eur_24h_change":1.3995546268340058,"gbp":13.62,"gbp_24h_change":1.578299526082951,"rub":1540.56,"rub_24h_change":1.779829692245149,"inr":1390.19,"inr_24h_change":1.5180234572949836,"cny":121.59,"cny_24h_change":1.5500166207540496,"try":475.67,"try_24h_change":1.4517189225851008,"cad":23.02,"cad_24h_change":1.6368619035650764,"dkk":116.48,"dkk_24h_change":1.4094523117738702},"29f74af9-6c7d-5021-9d52-30985310ab49":{"usd":56.96,"usd_24h_change":7.202508710562036,"eur":53.3,"eur_24h_change":7.1024747670140105,"gbp":46.47,"gbp_24h_change":7.291272648148503,"rub":5257.69,"rub_24h_change":7.504137286613963,"inr":4744.49,"inr_24h_change":7.227606528902378,"cny":414.96,"cny_24h_change":7.26139905387612,"try":1623.39,"try_24h_change":7.157572890374409,"cad":78.55,"cad_24h_change":7.353128694554922,"dkk":397.53,"dkk_24h_change":7.112929118173813},"2b74ef58-19d0-5263-8e2a-1d0232f1edf0":{"usd":0.958507,"usd_24h_change":null,"eur":0.895125,"eur_24h_change":null,"gbp":0.780135,"gbp_24h_change":null,"rub":87.97,"rub_24h_change":null,"inr":79.79,"inr_24h_change":null,"cny":6.98,"cny_24h_change":null,"try":27.31,"try_24h_change":null,"cad":1.32,"cad_24h_change":null,"dkk":6.68,"dkk_24h_change":null},"1d71b13d-12d6-50d2-922b-022966bc433a":{"usd":38.34,"usd_24h_change":0.476794407260074,"eur":35.87,"eur_24h_change":0.3893601256377099,"gbp":31.28,"gbp_24h_change":0.5657874069384939,"rub":3538.88,"rub_24h_change":0.7491058777941662,"inr":3193.45,"inr_24h_change":0.48776619667206406,"cny":279.31,"cny_24h_change":0.5319900644224611,"try":1092.68,"try_24h_change":0.43485742819174683,"cad":52.87,"cad_24h_change":0.6091984482730777,"dkk":267.57,"dkk_24h_change":0.3985409031602022},"fc9851b9-3bd7-5293-83c6-ccaa57ce1087":{"usd":0.0140007,"usd_24h_change":null,"eur":0.01413678,"eur_24h_change":null,"gbp":0.0121713,"gbp_24h_change":null,"rub":0.865593,"rub_24h_change":null,"inr":1.16,"inr_24h_change":null,"cny":0.102304,"cny_24h_change":null,"try":0.260622,"try_24h_change":null,"cad":0.01902139,"cad_24h_change":null,"dkk":0.105273,"dkk_24h_change":null},"06df45d9-dce1-557e-8b95-6092996677bc":{"usd":0.973756,"usd_24h_change":null,"eur":0.925777,"eur_24h_change":null,"gbp":0.801697,"gbp_24h_change":null,"rub":93.99,"rub_24h_change":null,"inr":81.02,"inr_24h_change":null,"cny":7.12,"cny_24h_change":null,"try":26.59,"try_24h_change":null,"cad":1.32,"cad_24h_change":null,"dkk":6.9,"dkk_24h_change":null},"efda8e83-d2da-5d38-b813-f0cf2ccce895":{"usd":0.01316626,"usd_24h_change":null,"eur":0.01227561,"eur_24h_change":null,"gbp":0.01064005,"gbp_24h_change":null,"rub":1.22,"rub_24h_change":null,"inr":1.094,"inr_24h_change":null,"cny":0.096128,"cny_24h_change":null,"try":0.374041,"try_24h_change":null,"cad":0.01799416,"cad_24h_change":null,"dkk":0.091595,"dkk_24h_change":null}},"trackedAssets":{"74cf0f2b-414c-53b7-bd2a-04f78b05aaad":{},"2db84be6-32ae-50e3-81b8-59694bef84a1":{},"054937d1-af4a-56cf-b807-5394352e7be8":{},"08a4164c-0989-5f1f-9315-1f4abe9b6bd5":{},"4ce50068-0edc-5243-a053-4efbbea6a406":{"cryptoCompareId":"TTV"},"4e7e2121-1f46-528b-bfe2-1fb1e2b512fb":{"cryptoCompareId":"AMB","cryptoCurrencyIconName":"amb"},"54bf63e5-7a23-59ee-805d-de9cc9425ae9":{},"615801c2-d042-5d4e-b7e1-4dea9d3982a7":{"cryptoCompareId":"BOXT"},"8462cdfd-2c20-5395-8f0d-1e9cd09a409f":{},"922f002a-707e-54e3-8277-94f0c1504e81":{"cryptoCurrencyIconName":"deez"},"9a986991-f7df-5bbb-a9a3-360977b57ab5":{},"a15526dc-57d5-50c7-8ba9-043f4b9dcfc7":{"cryptoCompareId":"SPHTX"},"be9dee32-93f5-5c86-9e89-eb0d497535cc":{},"c701b7d6-7506-5431-981a-333c47099b86":{"cryptoCompareId":"VIN"},"c7da0cdc-82b7-51af-9bed-abe9559b6fea":{"cryptoCompareId":"XNN"},"c9e2527d-128e-59d5-8e4a-b5cb427652b3":{"cryptoCompareId":"OAK"},"cf928db0-46bd-52c7-8056-c7a08cd5a1d9":{},"f0656669-66a1-5475-af6e-aeb454251845":{"cryptoCompareId":"HEX"},"1d2241f2-8f7f-50e5-b70f-cc2e33b1c4e9":{"cryptoCompareId":"SENT"},"2fdbfe5d-5e3a-5fe0-bcaa-42810867d1e6":{"cryptoCompareId":"SALT","dexAgId":"SALT"},"3c51b9f8-f813-5455-b4ce-7a9fa9f4975c":{"cryptoCompareId":"DEPO"},"6c52f4a7-6b8f-557c-aeb8-d064c5ea2c03":{"dexAgId":"SUSD"},"933d3751-169e-579c-a310-e649a8382317":{"cryptoCompareId":"SUSD","dexAgId":"SUSD"},"d0f5269a-78c6-5734-a6a7-0c9b46107582":{},"37055a94-c2bc-5f79-80c4-faaa93d1ff87":{},"66e28eb6-b405-5440-a277-bd4450f94537":{"cryptoCompareId":"DIP","dexAgId":"DIP"},"9e34106e-2062-535e-8111-3320b2008f58":{},"b7b4cc77-fb11-56d7-86e1-cd21165b4370":{"cryptoCompareId":"PAXG"},"eb2239a4-5c42-5429-bdc4-cbf28a22361b":{"coinGeckoId":"liquity-usd"}},"contracts":{},"networks":{},"notifications":{"98deb58d-f747-4570-9deb-9599ec503425":{"uuid":"98deb58d-f747-4570-9deb-9599ec503425","template":"save-settings","dateDisplayed":"2020-11-21T07:01:36.606Z","dismissed":false,"viewed":true},"86540e5f-9f20-4662-ab3e-9eb8c52e984d":{"uuid":"86540e5f-9f20-4662-ab3e-9eb8c52e984d","template":"wallet-added","templateData":{"address":"0xJordAnSPence.Eth"},"dateDisplayed":"2020-11-21T07:01:36.606Z","dismissed":true,"dateDismissed":"2020-12-16T02:36:49.188Z"},"2ade234f-0e44-4cf4-b055-8edcc8300c10":{"uuid":"2ade234f-0e44-4cf4-b055-8edcc8300c10","template":"onboarding-responsible","templateData":{"firstDashboardVisitDate":"2020-11-04T03:54:50.842Z"},"dateDisplayed":"2020-12-07T21:12:26.524Z","dismissed":true,"viewed":true,"dateDismissed":"2020-12-07T21:12:29.615Z"},"a4b524df-3428-4376-8ee0-3160528fe71b":{"uuid":"a4b524df-3428-4376-8ee0-3160528fe71b","template":"onboarding-please-understand","templateData":{"previousNotificationClosedDate":"2020-12-07T21:12:29.615Z"},"dateDisplayed":"2023-11-09T11:57:45.288Z","dismissed":true,"viewed":true,"dateDismissed":"2023-11-09T11:57:52.820Z"}},"settings":{"fiatCurrency":"USD","darkMode":false,"dashboardAccounts":["f535254d-4740-5b81-a333-b2440d785991"],"excludedAssets":[],"language":"en","isDemoMode":false,"canTrackProductAnalytics":true,"analyticsUserID":"88fw7hjxff2zxgdi4mzmc3","node":"web3"},"networkNodes":{},"userActions":{"a4536899-f118-4c18-bd03-defaaa12ead3":{"name":"migrate_gol","state":"hidden","uuid":"a4536899-f118-4c18-bd03-defaaa12ead3"},"ddd7f54f-7213-434f-a270-1e7336f7aa78":{"name":"telegram","state":"hidden","uuid":"ddd7f54f-7213-434f-a270-1e7336f7aa78"},"11f677ac-554d-4638-ac45-ac5e9c462823":{"name":"newsletter","state":"hidden","uuid":"11f677ac-554d-4638-ac45-ac5e9c462823"},"159376f3-f604-4199-b656-381fffdaa7df":{"name":"swap","state":"hidden","uuid":"159376f3-f604-4199-b656-381fffdaa7df"},"af5135c7-60c5-4023-83f1-866263eae81b":{"name":"twitter","state":"hidden","uuid":"af5135c7-60c5-4023-83f1-866263eae81b"},"d80b67e2-b4a2-455e-a25a-38556e354014":{"name":"migrate_ant","state":"new","uuid":"d80b67e2-b4a2-455e-a25a-38556e354014"},"ade94b9e-e186-46a6-8579-08e053013549":{"name":"buy_hw","state":"hidden","uuid":"ade94b9e-e186-46a6-8579-08e053013549"},"338c2135-56e7-4364-b43b-77fcf66dd6b6":{"name":"update_label","state":"completed","uuid":"338c2135-56e7-4364-b43b-77fcf66dd6b6"},"d6d71b9e-cb6a-4ff2-8465-34b79bff970e":{"name":"add_account","state":"new","uuid":"d6d71b9e-cb6a-4ff2-8465-34b79bff970e"},"39e66d3f-f932-4f98-bf8c-5e2039a92ce2":{"name":"myc_membership","state":"hidden","uuid":"39e66d3f-f932-4f98-bf8c-5e2039a92ce2"},"6df1ee49-d545-4631-8dad-ed2156741d00":{"name":"feedback","state":"hidden","uuid":"6df1ee49-d545-4631-8dad-ed2156741d00"},"e2c59196-42bd-4dc5-84be-af0c11ccbeeb":{"name":"backup","state":"hidden","uuid":"e2c59196-42bd-4dc5-84be-af0c11ccbeeb"},"206bda29-adbf-4acb-9d10-22d42badb0af":{"name":"myc_winter_start","state":"new","uuid":"206bda29-adbf-4acb-9d10-22d42badb0af"},"ba102a93-ba7d-46d3-9532-428501a6420b":{"name":"myc_winter_mid","state":"hidden","uuid":"ba102a93-ba7d-46d3-9532-428501a6420b"},"fce0fd16-f2c3-4b17-b867-072e0f5b33cd":{"name":"migrate_lend","state":"new","uuid":"fce0fd16-f2c3-4b17-b867-072e0f5b33cd"}},"promoPoaps":{"promos":{}},"connections":{"wallets":{}},"claims":{"claims":{"UNI":[{"address":"0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520","state":"NO_CLAIM","amount":"0x00"},{"address":"0x8000F432747ccDc71B9DF9F8eB96EFfeeac6218E","state":"CLAIMED","amount":"0x16205c76d84989f000","index":126824},{"address":"0xA42830eE059c77cAF8c8200B44AA9813CB0720c5","state":"NO_CLAIM","amount":"0x00"},{"address":"0xD132973EaEbBd6d7ca7b88e9170f2CCA058de430","state":"NO_CLAIM","amount":"0x00"}],"NODE":[{"address":"0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520","state":"NO_CLAIM","amount":"0x00"},{"address":"0x8000F432747ccDc71B9DF9F8eB96EFfeeac6218E","state":"NO_CLAIM","amount":"0x00"},{"address":"0xA42830eE059c77cAF8c8200B44AA9813CB0720c5","state":"NO_CLAIM","amount":"0x00"},{"address":"0xD132973EaEbBd6d7ca7b88e9170f2CCA058de430","state":"NO_CLAIM","amount":"0x00"}],"ENS":[{"address":"0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520","state":"CLAIMED","amount":"0xea19dab481c784000","index":38824},{"address":"0x8000F432747ccDc71B9DF9F8eB96EFfeeac6218E","state":"CLAIMED","amount":"0x7865c9e033da7f800","index":179179},{"address":"0xA42830eE059c77cAF8c8200B44AA9813CB0720c5","state":"NO_CLAIM","amount":"0x00"},{"address":"0xD132973EaEbBd6d7ca7b88e9170f2CCA058de430","state":"NO_CLAIM","amount":"0x00"}],"GIV":[{"address":"0xD132973EaEbBd6d7ca7b88e9170f2CCA058de430","state":"NO_CLAIM","amount":"0x00"}]},"error":true}}
