### ISSUE TITLE
**What does this PR do?**

### ISSUE THREAD

**Issue by Ahmed7683** [justswaporg/justlists#4075]
**What does this PR do?**
optimize resource usage recovery logic

**Why are these changes required?**
optimize resource usage recovery logic

**This PR has been tested by:**

- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

_Originally posted by @CarlChaoCarl in https://github.com/tronprotocol/protocol/pull/227_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
