### ISSUE TITLE
Let's say i have connected:

### ISSUE THREAD

**Issue by Ahmed7683** [justswaporg/justlists#4076]
Let's say i have connected:

- MetaMask
- Trust Wallet

I want to have some sort of sign message / send transaction buttons. Simple 0.0001 ETH transaction can be good as an example and message signing text can just be "Hello" .

Bonus:
Also this is not urgent, but if you could make sure whenever i connect a wallet and then reload a page i would like to see my wallets in a `connected` state instead of connecting my wallets again.

_Originally posted by @easyrun42 in https://github.com/WalletConnect/EIP6963/issues/44#issuecomment-1783087394_
            

_Originally posted by @Ahmed7683 in https://github.com/WalletConnect/EIP6963/issues/58_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
