### ISSUE TITLE
Kushshop 

### ISSUE THREAD

**Issue by Ysljarhead288** [justswaporg/justlists#4116]
curl --request POST \
     --url https://api.shasta.trongrid.io/wallet/getavailableunfreezecount \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "owner_address": "TZ4UXDV5ZhNW7fb2AMSbgfAEZ7hWsnYS2g",
  "visible": true
}
'

**Comment by Ysljarhead288** [comment]
curl --request POST \
     --url https://api.shasta.trongrid.io/wallet/getcanwithdrawunfreezeamount \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "owner_address": "TZ4UXDV5ZhNW7fb2AMSbgfAEZ7hWsnYS2g",
  "timestamp": 1667977444000,
  "visible": true
}
'

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
