### ISSUE TITLE
https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/functional-samples%2Ftutorial.hello-world%2Fmanifest.json#L1-L10

### ISSUE THREAD

**Issue by Danyalkasiri** [justswaporg/justlists#4126]
https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/functional-samples%2Ftutorial.hello-world%2Fmanifest.json#L1-L10

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
