### ISSUE TITLE
Add JustList: {BRIHLO}

### ISSUE THREAD

**Issue by brihlogold** [justswaporg/justlists#4139]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: www.brihlo.com
JustList Name: BRIHLO
Link to the official homepage of the JustList manager: https://brihlo.com

**Comment by brihlogold** [comment]
[Whitepaper BRIHLO - BRIL.pdf](https://github.com/justswaporg/justlists/files/14430447/Whitepaper.BRIHLO.-.BRIL.pdf)

**Comment by jz2120100058** [comment]
Hello, [brihlogold](https://github.com/brihlogold). Please first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf

Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.
Thanks

Note:
If the token satisfies the following four conditions, it will be automatically added to the "Tron Alliance List" :
1.The token page on Transcan has a official website
2.The token page on Transcan needs at least 1 social profile
3.In order of liquidity from most to least, select the top 10 tokens with 24-hour trading volume greater than $10,000.
4.If the tokens move back in the liquidity rankings or 24 hours trading volume less than $10,000 , the token will be removed

**Comment by jz2120100058** [comment]
https://github.com/justswaporg/justlists/issues/4149
