### ISSUE TITLE
https://github.com/ton-blockchain/ton/blob/master/tl%2Fgenerate%2Fscheme%2Ftonlib_api.tl#L235

### ISSUE THREAD

**Issue by Danyalkasiri** [justswaporg/justlists#4163]
https://github.com/ton-blockchain/ton/blob/master/tl%2Fgenerate%2Fscheme%2Ftonlib_api.tl#L235

**Comment by Danyalkasiri** [comment]
# - [ ] []()```
__
```

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
