### ISSUE TITLE
Add JustList

### ISSUE THREAD

**Issue by Cplus360** [justswaporg/justlists#4174]
Before submission deletes this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://justlists
JustList Name: 
Link to the official homepage of the JustList manager:
Lighting btc: lnbc1pnpsrtvdqdgdshx6pqg9c8qpp5zky3najk73vpsnrwsnzzrwxhdcs76zza6hsedea2znr6wjxxefdssp55deg0j6hnt6ejvt4xz2hdmngtwupd4z4k0jrxxe59ksaldqpzy7s9qrsgqcqpcxqy8ayqrzjqv06k0m23t593pngl0jt7n9wznp64fqngvctz7vts8nq4tukvtljqz9cqvqqzyqqqcqqqqqqqqqqqqqq9grzjqtsjy9p55gdceevp36fvdmrkxqvzfhy8ak2tgc5zgtjtra9xlaz97zv6fsqqsucqqyqqqqqqqqqqqqqq9gwnw53wt8u7ae3kc70ha77tfd87y94pwqlhq4r0evf59whq5zdqpxzh234uncg3ywgf7et5xmk4es4s7ptqkqk2075ly2fdxaxjajv2qqa44ck0

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
