### ISSUE TITLE
添加JustList: GDTList

### ISSUE THREAD

**Issue by GDTSSS** [justswaporg/justlists#4204]
JustList URL:  https://gdtsss.github.io/tokenlist/tokenlist.json
JustList 名称:  GDTLIST
JustList 提交者的网站或主页: https://gdtsss.github.io/tokenlist/tokenlist.json

**Comment by GDTSSS** [comment]
@jz2120100058

**Comment by GDTSSS** [comment]
@asi701070

**Comment by jz2120100058** [comment]
Hi, [GDTSSS](https://github.com/GDTSSS),Please first create createExchange in SunSwap by youself. Specific methods can be referred to https://www.sunswap.com/docs/sunswapV2-interfaces_en.pdf

Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

At last, you must submit correct website.
Thanks

**Comment by GDTSSS** [comment]
How to createExchange is not found in the pdf you provided. Is it createPair?
