### ISSUE TITLE
GDT (GDT)TOKEN

### ISSUE THREAD

**Issue by bibutb** [justswaporg/justlists#4207]
{
“symbol”：“GDT”，
“address”：“TASeVkpkMdGcyxDgrBwBdoV48rX2tHshPG”，
“chainId”：1，
“decimals”：18，
“name”：“GDT (GDT)TOKEN”，
“logoURI”：“https://static.tronscan.org/production/upload/logo/new/TASeVkpkMdGcyxDgrBwBdoV48rX2tHshPG.jpeg?t=1714814425938"
}

**Comment by bibutb** [comment]
> {“symbol”：“GDT”， “address”：“TASeVkpkMdGcyxDgrBwBdoV48rX2tHshPG”， “chainId”：1， “decimals”：18， “name”：“GDT （GDT）TOKEN”， “logoURI”[：“https://static.tronscan.org/production/upload/logo/new/TAXQKdGyWSZ5nrtgZLWZQmuyhPk1cHxPsL.jpeg?t=1714993703028](https://static.tronscan.org/production/upload/logo/new/TAXQKdGyWSZ5nrtgZLWZQmuyhPk1cHxPsL.jpeg?t=1714993703028)" }

**Comment by GDTSSS** [comment]
@asi701070
