### ISSUE TITLE
Add JustList: GDTSwap Default List

### ISSUE THREAD

**Issue by hi-andy** [justswaporg/justlists#4221]
JustList URL: [GDTSwap Default List](https://gdtcoin.cc/gdtlist.json)
JustList Name: GDTSwap Default List
Link to the official homepage of the JustList manager: https://gdtcoin.cc/

**Comment by jz2120100058** [comment]
Hi, [hi-andy](https://github.com/hi-andy)，I hope you have a good day.
Please first create createPair in SunSwap by youself. 

Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance.

At last, you must submit correct website.
Thanks

**Comment by jz2120100058** [comment]
https://github.com/justswaporg/justlists/issues/4220
