### ISSUE TITLE
Add JustList: {JustSwap Default List}

### ISSUE THREAD

**Issue by Reitr0** [justswaporg/justlists#4225]
Checklist
- [y] **I understand that this is not the place to request a token listing.**
- [y] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [y] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://github.com/Reitr0/justlist
JustList Name: JustSwap Default List
Link to the official homepage of the JustList manager: https://sunswap.com/#/home

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by Reitr0** [comment]
> Please submit the correct information, invalid information will cause the issue to close

i don't really understand what is the wrong info
