### ISSUE TITLE
**PR Summary**

### ISSUE THREAD

**Issue by Masoodshafiee** [justswaporg/justlists#4232]
**PR Summary** 
Files OK, 8Files in PR:  8 
Tokens in PR (4): 
- BEP2 TUSDB-888
- ERC20 0x0000000000085d4780B73119b644AE5ecd22b376
- BEP20 0x14016e85a25aeb13065688cafb43044c2ef86784
- TRC20 TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4

 
----- 
**Token BEP2 - TUSDB-888**: 
Symbol: **TUSDB** decimals: 8  
Links: [Logo](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/binance/assets/TUSDB-888/logo.png) [Info](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/binance/assets/TUSDB-888/info.json) [Website](https://www.trueusd.com/) [Explorer](https://explorer.binance.org/asset/TUSDB-888) 
Token check error: 
!  No. of holders not checked, external info not available; null
✓  Token type OK (BEP2); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (15.64 kB); Logo dimensions OK (256x256); 
 

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/binance/assets/TUSDB-888/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span> 

 
----- 
**Token ERC20 - 0x0000000000085d4780B73119b644AE5ecd22b376**: 
Symbol: **TUSD** decimals: 18  
Links: [Logo](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/logo.png) [Info](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json) [Website](https://www.trueusd.com/) [Explorer](https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376) (check OK 🙂)  

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span> 

 
----- 
**Token BEP20 - 0x14016e85a25aeb13065688cafb43044c2ef86784**: 
Symbol: **TRUEUSD** decimals: 18  
Links: [Logo](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/smartchain/assets/0x14016e85a25aeb13065688cafb43044c2ef86784/logo.png) [Info](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/smartchain/assets/0x14016e85a25aeb13065688cafb43044c2ef86784/info.json) [Website](https://www.trueusd.com/) [Explorer](https://bscscan.com/token/0x14016e85a25aeb13065688cafb43044c2ef86784) 
Token check error: 
❌  Contract is not in checksum format, should be 0x14016E85a25aeb13065688cAFB43044C2ef86784 (not 0x14016e85a25aeb13065688cafb43044c2ef86784). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
❌  Symbol does not match token info, expected 'TUSD' instead of 'TRUEUSD', please change.
✓  Token type OK (BEP20); Type field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (15.64 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 8738); 
 

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/smartchain/assets/0x14016e85a25aeb13065688cafb43044c2ef86784/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span> 

 
----- 
**Token TRC20 - TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4**: 
Symbol: **TrueUSD** decimals: 18  
Links: [Logo](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/tron/assets/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4/logo.png) [Info](https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/tron/assets/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4/info.json) [Website](https://www.trueusd.com/) [Explorer](https://tronscan.io/#/token20/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4) 
Token check error: 
!  No. of holders not checked, external info not available; null
✓  Token type OK (TRC20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (15.64 kB); Logo dimensions OK (256x256); 
 

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/RandomGly/assets/master/blockchains/tron/assets/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span> 

_Originally posted by @ghost in https://github.com/trustwallet/assets/pull/12649#issuecomment-895776087_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
