### ISSUE TITLE
添加JustList: stablecoin list

### ISSUE THREAD

**Issue by sw7837** [justswaporg/justlists#4255]
JustList URL: https://github.com/sw7837/justlist.git
JustList 名称: stablecoin list
JustList 提交者的网站或主页: https://eurotoken.vip

**Comment by jz2120100058** [comment]
Hi, [sw7837](https://github.com/sw7837).
Please first create createPair in SunSwap by youself.

Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance. However, its requirements are very strict. You can refer to  https://github.com/justswaporg/justlists/issues/4254

At last, you must submit an accessible website.
Thanks

**Comment by sw7837** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello, do I just copy the contents of this tronalliance.json file and resubmit it?
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                nick7837
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年05月31日 16:23
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [justswaporg/justlists] 添加JustList: stablecoin list (Issue #4255)
        
      
    
  
  
Hi, sw7837.
Please first create createPair in SunSwap by youself.
Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance. However, its requirements are very strict. You can refer to
At last, you must submit an accessible website.
Thanks

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jz2120100058** [comment]
You have to meet tronalliance's requirements before you can go through the rest of the process
