### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by Wangyy471** [justswaporg/justlists#4261]
{
    "name":"JustSwap Default List",
    "tokens":[
        {  "symbol":"USDT",
            "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        }],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
