### ISSUE TITLE
Please submit the correct information, invalid information will cause the issue to close

### ISSUE THREAD

**Issue by KVR180292** [justswaporg/justlists#4302]
Please submit the correct information, invalid information will cause the issue to close

_Originally posted by @jz2120100058 in https://github.com/justswaporg/justlists/issues/4286#issuecomment-2208551152_

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by KVR180292** [comment]
Thx.. Im still learning...
