### ISSUE TITLE
https://web3.bitget.com/en/?utm_source=NFTPaymentCodeShare

### ISSUE THREAD

**Issue by Whatafac** [justswaporg/justlists#4303]
I'm using BitgetWallet!
👍 The smoothest Web3 wallet user experience I've had
💰 Finding the key to prosperity here every day!
https://web3.bitget.com/en/?utm_source=NFTPaymentCodeShare![807.png](https://github.com/justswaporg/justlists/assets/111152019/57db5be6-6a31-471d-90be-9afc6eb3fb42)

**Comment by Whatafac** [comment]
https://web3.bitget.com/en/?utm_source=NFTPaymentCodeShare

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
