### ISSUE TITLE
Add JustList: {X}

### ISSUE THREAD

**Issue by aitelong** [justswaporg/justlists#4334]
{
            "symbol":"X",
            "address":"TVWwjAYjSNrNBK7q62pgkNz6ahSyDXVTs8",
            "chainId":1,
            "decimals":18,
            "name":"X",
            "logoURI":"https://github.com/aitelong/X/blob/main/X.jpg"
        },

**Comment by aitelong** [comment]
I hope you can help.

**Comment by jz2120100058** [comment]
Hi, [aitelong](https://github.com/aitelong)，I hope you have a good day.
Please first create createPair in SunSwap by youself.

Second, We are currently very tight on development resources and adding new lists, If timing is a key issue for you, we recommend you join the existing community SUNSWAP list, for example: Tron Alliance List: https://github.com/listtronalliance/tronalliance. However, its requirements are very strict.

At last, you must submit correct website.
Thanks

**Comment by jz2120100058** [comment]
You can refer to https://sun.io/?lang=zh-CN#/sun_swap/v2?t0=T9yD14Nj9j7xAB4dbGeiX9h8unkKHxuWwb&type=swap&from=v3

**Comment by aitelong** [comment]
> Thanks

I need to edit it anew, right?

**Comment by aitelong** [comment]
I've edited it again. Is this okay?

**Comment by aitelong** [comment]
Could you please take a look at this?
