### ISSUE TITLE
updated_custom_token_list.json

### ISSUE THREAD

**Issue by crazyfrog4343** [justswaporg/justlists#4356]
[updated_custom_token_list.json](https://github.com/user-attachments/files/16683235/updated_custom_token_list.json)

**Comment by jz2120100058** [comment]
Please fill out the application in the correct format. Incorrect formats will result in the issue being closed.

**Comment by meemijung** [comment]
> [updated_custom_token_list.json](https://github.com/user-attachments/files/16683235/updated_custom_token_list.json)
