### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by aybmiliom** [justswaporg/justlists#4413]
const swap = await contract.methods.swapExactETHForTokens(
trx_amount,
[
  "TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",
  "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
],
"TRpZ1F9xxxxxxxxxxxxxxxxxxxxxxxx",
deadline
 ).send({value:trx_amount});

**Comment by jz2120100058** [comment]
Please fill out the application in the correct format. Incorrect formats will result in the issue being closed.
