### ISSUE TITLE
X

### ISSUE THREAD

**Issue by aitelong** [justswaporg/justlists#4416]
{
   "name": "X", 
   "logoURI": "https://github.com/aitelong/X/blob/main/X.jpg", 
   "timestamp": 1611147166000, 
   "tokens": [{
           "chainId": 1,
           "address": "TVWwjAYjSNrNBK7q62pgkNz6ahSyDXVTs8",
           "name": "X",
           "symbol": "X",
           "decimals": 18,
           "logoURI": "https://github.com/aitelong/X/blob/main/X.jpg"
       }
   ],
   "version": { 
       "major": 1, 
       "minor": 0, 
       "patch": 0  
   }

**Comment by jz2120100058** [comment]
Please fill out the application in the correct format. Incorrect formats will result in the issue being closed. Also, please confirm that a liquidity pool has been created on SunSwap.
