### ISSUE TITLE
Add JustList: DeFi25

### ISSUE THREAD

**Issue by Tron47** [justswaporg/justlists#541]
{
   "name": "DeFi25",
   "logoURI": "https://coin.top/production/upload/logo/TBHoEERmt1Qx8TMbC8ScnUvXXejwWWG4RG.png",
   "timestamp": 1614515761737,
   "tokens": [{
           "chainId": 1,
           "address": "TBHoEERmt1Qx8TMbC8ScnUvXXejwWWG4RG",
           "name": "DeFi25",
           "symbol": "DF25",
           "decimals": 18,
           "logoURI": "https://coin.top/production/upload/logo/TBHoEERmt1Qx8TMbC8ScnUvXXejwWWG4RG.png"
       },
   ],
   "version": { #Version info
       "major": 1, #Major version
       "minor": 0, #Minor version
       "patch": 0  #Patch version
   }
}

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
