### ISSUE TITLE
TETRA

### ISSUE THREAD

**Issue by baronred2020** [justswaporg/justlists#568]
**YOUR JUSTLIST MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/justswaporg/justlists/pull/573/commits/7b64d75e35d60a22b694fa618d544c392e9b000e#diff-7935345ecb00d84308c12074d9b891cfcaede91cdb2675932b0d9009ec888783

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://youtetra.com/tokenlist.json
JustList Name: TETRA
Link to the official homepage of the JustList manager: https://youtetra.com/

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
