### ISSUE TITLE
Add JustList: {JustList SVV}

### ISSUE THREAD

**Issue by Taleshcoin** [justswaporg/justlists#608]
https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://tronscan.org/#/token20/TBQoSyHRkcBkRyAbEWRYmbSa6PUSuRh45j
JustList Name: SVV
Link to the official homepage of the JustList manager: https://justswap.org/?lang=en-US#/scan/detail/trx/TBQoSyHRkcBkRyAbEWRYmbSa6PUSuRh45j

**Comment by jeffwami** [comment]
Repeat #610
