### ISSUE TITLE
Add JustList: {JustList VACCINE}

### ISSUE THREAD

**Issue by Taleshcoin** [justswaporg/justlists#610]
https://gist.github.com/Taleshcoin/d7acd8592ecbabdfd37aab3d04d6d21a

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://gist.github.com/Taleshcoin/d7acd8592ecbabdfd37aab3d04d6d21a
JustList Name: SVV
Link to the official homepage of the JustList manager: https://github.com/Taleshcoin

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
