### ISSUE TITLE
Add JustList: {JustList TALC}

### ISSUE THREAD

**Issue by Taleshcoin** [justswaporg/justlists#611]
https://gist.github.com/Taleshcoin/27dd075e0065d3b7fdf08dd1a2d2c607

Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://gist.github.com/Taleshcoin/27dd075e0065d3b7fdf08dd1a2d2c607
JustList Name: TALC
Link to the official homepage of the JustList manager: https://github.com/Taleshcoin

**Comment by Taleshcoin** [comment]
https://justswap.org/?lang=en-US#/scan/detail/trx/TEhiPMs7EUCVBcboVw7UE6J3gGR1SY6RE2

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
