### ISSUE TITLE
spark

### ISSUE THREAD

**Issue by huanjinjin** [justswaporg/justlists#661]
检查清单
- [x] **我已知晓此issue不是提交token而是提交JustList**
- [x] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [x] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: https://profile.tokenpocket.pro/?locale=zh-CN&utm_source=tokenpocket#/token/48666019
JustList 名称: spark
JustList 提交者的网站或主页:

https://user-images.githubusercontent.com/69407539/110820321-f2e40800-82c9-11eb-9af3-a39092a3bd6d.jpg)
#657

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
