### ISSUE TITLE
添加JustList: {JustList name}

### ISSUE THREAD

**Issue by huanjinjin** [justswaporg/justlists#663]
{
    "name":"JustSwap Default List",
    "tokens":[21000000
        {
            "symbol":"SPK",
            "address":"TCZzRquGL9vWcad9jRZB11vdYSExtkePMP",
            "chainId":1,
            "decimals":18,
            "name":"SPK TOKEN",
            "logoURI":"https://user-images.githubusercontent.com/69407539/110820321-f2e40800-82c9-11eb-9af3-a39092a3bd6d.jpg"
        },
检查清单
- [ ] **我已知晓此issue不是提交token而是提交JustList**
- [ ] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [ ] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.
https://justswap.io/?utm_source=tokenpocket#/home
JustList URL: https://profile.tokenpocket.pro/?locale=zh-CN&utm_source=tokenpocket#/token/48666019
JustList 名称: spk1
JustList 提交者的网站或主页:

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
