### ISSUE TITLE
Swap 500 trx jadi DWB hilang tidak masuk ke walet tronlik

### ISSUE THREAD

**Issue by supandi70** [justswaporg/justlists#741]
Swap 500 trx jadi DWB hilang tidak masuk ke walet tronlik 
Solusinya bagaimana ???
Jadi rugi..

_Originally posted by @supandi70 in https://github.com/justswaporg/justlists/issues/740#issuecomment-803436922_

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
