### ISSUE TITLE
Add JustList: {JustList name}

### ISSUE THREAD

**Issue by vandy247396** [justswaporg/justlists#801]
RESPECTED SIR KINDLY 
ADD  ETHEREUM VAULT  (ETHV )
TFc3XocoSMbqNjptsGHSVEeaP9pxg8V34U

IN JUST SWAP LIST ...................

THANKING YOU 
AFTER SEARCH IN TOKEN NOT SEEN 
THANKING YOU

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
