### ISSUE TITLE
Add JustList: ZOE JustList

### ISSUE THREAD

**Issue by zoetoken** [justswaporg/justlists#85]
Checklist
- [x] **I understand that this is not the place to request a token listing.**
- [x] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://list.zoetoken.org/justswap.json
JustList Name: ZOE JustList
Link to the official homepage of the JustList manager: https://list.zoetoken.org

**Comment by jeffwami** [comment]
Repeat #111
