### ISSUE TITLE
Fila添加JustList: {JustList name}

### ISSUE THREAD

**Issue by 15966278166** [justswaporg/justlists#909]
https://github.com/justswaporg/justlists/blob/main/example.justlists.ts

检查清单
- [ ] **我已知晓此issue不是提交token而是提交JustList**
- [ ] 我已经测试粘贴JustList URL到`justswap.org`的`添加列表`中并能够正常展示.
- [ ] 我已知晓提交的issue不能确保通过并且提交的JustList不确保能在jsutlists网站中显示.

**请提供以下的信息**
JustList的json URL必须以HTTPS开头.

JustList URL: TYtgUMrB1H72SqQDNCVNRn1DNYxqn8Qfxr

JustList 名称: fila
JustList 提交者的网站或主页:

**Comment by 15966278166** [comment]
涂鸦

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
