### ISSUE TITLE
Add JustList: BEGU

### ISSUE THREAD

**Issue by begundal123** [justswaporg/justlists#956]
{
   "name": BEGU
   "logoURI": 
   "timestamp": 1610339529000, #Update time in millisecond
   "tokens": [{
           "chainId": 1, #ChainId, which is currently 1
           "address": "TFNrxiTkx6DrJY8UhJSj27AwUFag983bgt"
           "name": "BEGU"
           "symbol": "BEGU"
           "decimals": 8, #Token decimals
       },

**Comment by JustSwapTeam** [comment]
Sorry, but your issue will be closed because you did not submit your information in the correct format.
