### ISSUE TITLE
Add JustList: {Lovecointoken}

### ISSUE THREAD

**Issue by KiritoSniper01** [justswaporg/justlists#962]
Before submission deletes this line:

https://github.com/justswaporg/justlists/example.justlists.ts

Checklist
- [X] **I understand that this is not the place to request a token listing.**
- [] I have tested that my JustList is compatible by pasting the URL into the `add a list` UI at `justswap.org`.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the justlists website.

**Please provide the following information for your token.**
JustList URL must be HTTPS.

JustList URL: https://lovecointoken.com/ 
JustList Name: {Lovecointoken}
Link to the official homepage of the JustList manager: https://lovecointoken.com/ 
https://lovecointoken.com/wp-content/uploads/Lovecoin-Whitepaper-2.pdf

**Comment by jeffwami** [comment]
Sorry, your issue will be closed as you did not submit your information in the correct format.
